# -*- coding: utf-8 -*-
"""Desafio da Diabetes

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1O1-Za-17akGfjcixvRQNLHwGAWAEl4n8

# Desafio da Diabetes - Árvore de Decisão

# Atividade Avaliativa

### Membros

Edson Macield e Barros Junior - 20210010250


Neste desafio, aplicamos o algoritmo de **Árvore de Decisão** para um problema de classificação.

O objetivo é classificar as espécies da flor Iris com base em suas características físicas.

Esse problema foi estudado em aula como exemplo de **aprendizado supervisionado (classificação)**.

## 📌 Atributos utilizados:
- Comprimento da sépala
- Largura da sépala
- Comprimento da pétala
- Largura da pétala

## 🎯 Saída:
- Espécie da flor (Setosa, Versicolor ou Virginica)
"""

# ==============================
# IMPORTAÇÃO DAS BIBLIOTECAS
# ==============================

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier, plot_tree
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# ==============================
# CARREGAMENTO DE DADOS
# ==============================

# Link da base de dados Iris
url = "https://raw.githubusercontent.com/ect-info/ml/master/dados/Iris.csv"

# Lendo o dataset
df = pd.read_csv(url)

# Visualizando as primeiras linhas
df.head()

# ==============================
# ANÁLISE INICIAL
# ==============================

# Informações do dataset
df.info()

# Estatísticas descritivas
df.describe()

# ==============================
# PREPARAÇÃO DOS DADOS
# ==============================

# Separando variáveis de entrada (X) e saída (y)

X = df[['SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm']].values
y = df['Species'].values

# Visualizando exemplos
print("X (entrada):")
print(X[:5])

print("\ny (saída):")
print(y[:5])

# ==============================
# DIVISÃO TREINO E TESTE
# ==============================

# Separando dados em treino e teste

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

print(f"Tamanho treino: {X_train.shape}")
print(f"Tamanho teste: {X_test.shape}")

# ==============================
# TREINAMENTO DA ÁRVORE
# ==============================

# Criando o modelo de árvore de decisão
modelo = DecisionTreeClassifier(
    max_depth=3,       # limita profundidade
    criterion='entropy' # usa entropia
)

# Treinando o modelo
modelo.fit(X_train, y_train)

# ==============================
# VISUALIZAÇÃO DA ÁRVORE
# ==============================

# Plotando a árvore de decisão

plt.figure(figsize=(12, 6))

plot_tree(
    modelo,
    feature_names=['SepalLength', 'SepalWidth', 'PetalLength', 'PetalWidth'],
    class_names=modelo.classes_,
    filled=True
)

plt.title("Árvore de Decisão - Iris")
plt.show()

# ==============================
# AVALIAÇÃO DO MODELO
# ==============================

# Fazendo previsões
y_pred = modelo.predict(X_test)

# Acurácia
acc = accuracy_score(y_test, y_pred)
print(f"Acurácia: {acc:.4f}")

# Matriz de confusão
cm = confusion_matrix(y_test, y_pred)
print("Matriz de Confusão:")
print(cm)

# ==============================
# GRÁFICO EXTRA (DIFERENCIAL)
# ==============================

# Comparação real vs predito (visual simples)

plt.figure()

plt.scatter(range(len(y_test)), y_test, label="Real")
plt.scatter(range(len(y_pred)), y_pred, marker='x', label="Predito")

plt.title("Comparação Real vs Predito")
plt.legend()

plt.show()

# ==============================
# TESTE COM NOVA AMOSTRA
# ==============================

# Nova flor para teste

nova_flor = [[5.1, 3.5, 1.4, 0.2]]

# Previsão
resultado = modelo.predict(nova_flor)

print(f"Espécie prevista: {resultado[0]}")

# ==============================
# HEATMAP DA MATRIZ
# ==============================

plt.figure()
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues')

plt.title("Matriz de Confusão")
plt.xlabel("Predito")
plt.ylabel("Real")

plt.show()

# ==============================
# IMPORTÂNCIA DAS VARIÁVEIS
# ==============================

importancias = modelo.feature_importances_

plt.figure()
plt.bar(['SepalL', 'SepalW', 'PetalL', 'PetalW'], importancias)

plt.title("Importância das Features")
plt.ylabel("Importância")

plt.show()

# ==============================
# DIFERENTES PROFUNDIDADES
# ==============================

for depth in range(1, 6):
    modelo_temp = DecisionTreeClassifier(max_depth=depth, criterion='entropy')
    modelo_temp.fit(X_train, y_train)

    y_pred_temp = modelo_temp.predict(X_test)
    acc = accuracy_score(y_test, y_pred_temp)

    print(f"Profundidade {depth}: Acurácia = {acc:.4f}")

# ==============================
# DESEMPENHO
# ==============================

profundidades = []
acuracias = []

for depth in range(1, 10):
    modelo_temp = DecisionTreeClassifier(max_depth=depth)
    modelo_temp.fit(X_train, y_train)

    y_pred_temp = modelo_temp.predict(X_test)
    acc = accuracy_score(y_test, y_pred_temp)

    profundidades.append(depth)
    acuracias.append(acc)

plt.figure()
plt.plot(profundidades, acuracias)

plt.title("Acurácia vs Profundidade")
plt.xlabel("Profundidade")
plt.ylabel("Acurácia")

plt.show()

# ==============================
# COMPARAR RANDOM FOREST
# ==============================

modelo_rf = RandomForestClassifier(n_estimators=100)
modelo_rf.fit(X_train, y_train)

y_pred_rf = modelo_rf.predict(X_test)

acc_rf = accuracy_score(y_test, y_pred_rf)

print(f"Acurácia Random Forest: {acc_rf:.4f}")

print(classification_report(y_test, y_pred))

"""## Conclusão

O modelo de Árvore de Decisão apresentou bom desempenho na classificação das espécies de flores Iris, alcançando alta acurácia.

A utilização do critério de entropia permitiu selecionar os melhores atributos para divisão dos dados, resultando em uma árvore interpretável.

Além disso, a visualização da árvore facilita a compreensão do processo de decisão do modelo, sendo uma das principais vantagens desse algoritmo.

Essa atividade reforçou os conceitos de classificação supervisionada e avaliação de modelos vistos em aula.
"""