# -*- coding: utf-8 -*-
"""Treinar uma SVM

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1detl63wSgPHF_r70ckgh21yKe5Y-53Yb

#SVM - TITANIC

Automatically generated by Colab.

## Atividade Avaliativa

### Membros

Edson Maciel e Barros Junior - 20210010250

Neste projeto, aplicamos o algoritmo de **Support Vector Machine (SVM)**
para um problema de classificação.

O objetivo é prever quais passageiros sobreviveram ao acidente do Titanic.

## 📌 Atributos utilizados:
- Classe (Pclass)
- Sexo (Sex)
- Idade (Age)
- Número de irmãos/cônjuges (SibSp)
- Número de pais/filhos (Parch)
- Tarifa (Fare)

## 🎯 Saída:
- Sobreviveu (1) ou Não (0)
"""

# ==============================
# IMPORTAÇÃO DAS BIBLIOTECAS
# ==============================

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# ==============================
# CARREGAMENTO DOS DADOS
# ==============================

df = pd.read_csv("train.csv")

df.head()

# ==============================
# ANÁLISE INICIAL
# ==============================

df.info()
df.describe()

print(df.columns)

# ==============================
# TRATAMENTO DOS DADOS
# ==============================

# Selecionando colunas relevantes
df = df[['Survived', 'Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare']]

# Tratando valores nulos
df['Age'].fillna(df['Age'].median(), inplace=True)
df['Fare'].fillna(df['Fare'].median(), inplace=True)

# Convertendo variável categórica
le = LabelEncoder()
df['Sex'] = le.fit_transform(df['Sex'])

# ==============================
# ANÁLISE VISUAL
# ==============================

plt.figure()
sns.countplot(x='Survived', data=df)
plt.title("Distribuição de Sobreviventes")
plt.show()

plt.figure()
sns.boxplot(data=df[['Age', 'Fare']])
plt.title("Boxplot das Variáveis")
plt.show()

# ==============================
# SEPARAÇÃO DOS DADOS
# ==============================

X = df.drop('Survived', axis=1)
y = df['Survived']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# ==============================
# NORMALIZAÇÃO (IMPORTANTE PARA SVM)
# ==============================

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# ==============================
# TREINAMENTO DO MODELO
# ==============================

modelo = SVC(kernel='rbf', C=1.0, gamma='scale')

modelo.fit(X_train, y_train)

# ==============================
# AVALIAÇÃO
# ==============================

y_pred = modelo.predict(X_test)

acc = accuracy_score(y_test, y_pred)
print(f"Acurácia: {acc:.4f}")

print("\nRelatório de Classificação:")
print(classification_report(y_test, y_pred))

# ==============================
# MATRIZ DE CONFUSÃO
# ==============================

cm = confusion_matrix(y_test, y_pred)

plt.figure()
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues')

plt.title("Matriz de Confusão")
plt.xlabel("Predito")
plt.ylabel("Real")

plt.show()

# ==============================
# TESTE DE DIFERENTES KERNELS
# ==============================

kernels = ['linear', 'rbf', 'poly']
acuracias = []

for k in kernels:
    modelo_temp = SVC(kernel=k)
    modelo_temp.fit(X_train, y_train)

    y_pred_temp = modelo_temp.predict(X_test)
    acc_temp = accuracy_score(y_test, y_pred_temp)

    acuracias.append(acc_temp)
    print(f"Kernel {k}: {acc_temp:.4f}")

# Gráfico comparação
plt.figure()
plt.plot(kernels, acuracias, marker='o')

plt.title("Acurácia por Kernel")
plt.xlabel("Kernel")
plt.ylabel("Acurácia")

plt.show()

# ==============================
# DISTRIBUIÇÃO DAS VARIÁVEIS
# ==============================

plt.figure(figsize=(10,6))
corr = pd.DataFrame(X).corr()

sns.heatmap(corr, cmap='coolwarm')
plt.title("Matriz de Correlação")

plt.show()

"""## Conclusão

O modelo SVM apresentou bom desempenho na classificação dos passageiros
sobreviventes do Titanic.

A normalização dos dados foi essencial para o funcionamento adequado do modelo.

O kernel RBF apresentou melhor desempenho em comparação aos outros testados.

Além disso, foi possível observar que variáveis como sexo, classe e idade
têm grande influência na sobrevivência dos passageiros.

O SVM se mostrou uma técnica eficiente para problemas de classificação binária.
"""