# -*- coding: utf-8 -*-
"""Algoritmo-de-ML-para-classificar-texto

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qJpHiB4EuetgyzeO-xnQABKrpaS9xToV

## 🧠 Classificação de Texto com Machine Learning

## 📚 Atividade Avaliativa

### 👥 Membros
Edson Maciel e Barros Junior - 20210010250

---

## 📖 Introdução

Neste projeto, foi desenvolvido um modelo de **Machine Learning para classificação de textos**, utilizando técnicas de aprendizado supervisionado aplicadas a dados textuais.

O objetivo principal é treinar um algoritmo capaz de **interpretar textos e atribuir automaticamente uma classe ou categoria**, como por exemplo spam/não spam ou sentimento positivo/negativo, dependendo da base de dados escolhida.

---

## 🔬 Abordagem do problema

Para resolver o problema de classificação textual, foi utilizada uma pipeline típica de processamento de linguagem natural (NLP), incluindo:

- 📥 Coleta de dados a partir de uma base disponível no Kaggle  
- 🧹 Pré-processamento e limpeza dos textos  
- 🔤 Transformação dos textos em representação numérica (Bag of Words / TF-IDF)  
- 🤖 Treinamento de modelos de Machine Learning supervisionado  
- 📊 Avaliação do desempenho do modelo  

---

## 📊 Base de dados

A base de dados utilizada foi escolhida no Kaggle e contém textos rotulados, permitindo o treinamento de modelos supervisionados.

Esses dados podem representar diferentes problemas de classificação, como:
- Spam vs não spam
- Sentimento (positivo/negativo)
- Categorias de notícias

---

## 🎯 Objetivo do projeto

Este projeto tem como objetivo demonstrar a aplicação de técnicas de **Processamento de Linguagem Natural (NLP)** combinadas com **Machine Learning supervisionado**, visando construir um modelo capaz de classificar textos de forma automática e eficiente.
"""

# ==========================================
# 🧠 CLASSIFICAÇÃO DE TEXTO - ML (NLP)
# ==========================================

# 📦 1. IMPORTAR BIBLIOTECAS
import pandas as pd
import numpy as np
import re
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.pipeline import Pipeline
from wordcloud import WordCloud

# ==========================================
# 📥 2. CARREGAR DATASET
# ==========================================

from google.colab import files
uploaded = files.upload()

df = pd.read_csv("spam.csv", encoding="latin-1")

df = df[['v1', 'v2']]
df.columns = ['label', 'text']

print(df.head())

# ==========================================
# 🧹 3. LIMPEZA DE TEXTO
# ==========================================

def clean_text(text):
    text = text.lower()
    text = re.sub(r'[^a-zA-Z]', ' ', text)
    text = re.sub(r'\s+', ' ', text)
    return text

df['text'] = df['text'].apply(clean_text)

# ==========================================
# ✂️ 4. SPLIT
# ==========================================

X_train, X_test, y_train, y_test = train_test_split(
    df['text'],
    df['label'].map({'ham': 0, 'spam': 1}),
    test_size=0.2,
    random_state=42
)

# ==========================================
# 🤖 5. PIPELINES
# ==========================================

pipe_nb = Pipeline([
    ('tfidf', TfidfVectorizer(stop_words='english')),
    ('model', MultinomialNB())
])

pipe_lr = Pipeline([
    ('tfidf', TfidfVectorizer(stop_words='english')),
    ('model', LogisticRegression(max_iter=1000))
])

# TREINAMENTO
pipe_nb.fit(X_train, y_train)
pipe_lr.fit(X_train, y_train)

# ==========================================
# 📊 6. PREDIÇÕES
# ==========================================

pred_nb = pipe_nb.predict(X_test)
pred_lr = pipe_lr.predict(X_test)

print("📌 Naive Bayes Accuracy:", accuracy_score(y_test, pred_nb))
print("📌 Logistic Regression Accuracy:", accuracy_score(y_test, pred_lr))

print("\n📌 Classification Report (Logistic Regression):\n")
print(classification_report(y_test, pred_lr))

# ==========================================
# 📉 7. MATRIZ DE CONFUSÃO
# ==========================================

cm = confusion_matrix(y_test, pred_lr)

plt.figure(figsize=(5,4))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues')
plt.title("Matriz de Confusão - Logistic Regression")
plt.xlabel("Previsto")
plt.ylabel("Real")
plt.show()

# ==========================================
# ☁️ 8. WORDCLOUD
# ==========================================

spam_text = " ".join(df[df['label'] == 'spam']['text'])
ham_text = " ".join(df[df['label'] == 'ham']['text'])

wordcloud_spam = WordCloud(width=800, height=400, background_color='black').generate(spam_text)
wordcloud_ham = WordCloud(width=800, height=400, background_color='white').generate(ham_text)

plt.figure(figsize=(10,5))
plt.imshow(wordcloud_spam)
plt.title("WordCloud - SPAM")
plt.axis("off")
plt.show()

plt.figure(figsize=(10,5))
plt.imshow(wordcloud_ham)
plt.title("WordCloud - HAM")
plt.axis("off")
plt.show()

# ==========================================
# 🔍 9. GRIDSEARCHCV
# ==========================================

pipeline = Pipeline([
    ('tfidf', TfidfVectorizer()),
    ('model', LogisticRegression(max_iter=1000))
])

params = {
    'tfidf__ngram_range': [(1,1), (1,2)],
    'model__C': [0.1, 1, 10]
}

grid = GridSearchCV(pipeline, params, cv=3, n_jobs=-1, verbose=1)
grid.fit(X_train, y_train)

print("📌 Melhor modelo:", grid.best_params_)
print("📌 Melhor score:", grid.best_score_)

# ==========================================
# 🔮 10. TESTE FINAL
# ==========================================

def predict_message(msg):
    msg = clean_text(msg)
    pred = pipe_lr.predict([msg])
    return "SPAM 🚨" if pred[0] == 1 else "HAM ✅"

print(predict_message("Congratulations! You won a free iPhone"))
print(predict_message("Are we meeting today?"))

"""# 🏁 Conclusão

Neste projeto, foi desenvolvido um sistema de **classificação de textos utilizando técnicas de Machine Learning e Processamento de Linguagem Natural (NLP)**.

A partir da base de dados SMS Spam Collection, foi possível treinar modelos capazes de distinguir mensagens entre **spam e ham (não spam)** com alta precisão.

---

## 📊 Principais resultados

- O modelo **Logistic Regression** apresentou desempenho superior em relação ao Naive Bayes em termos gerais de métricas como precisão e F1-score.
- O modelo alcançou aproximadamente **97% de acurácia**, demonstrando boa capacidade de generalização.
- A **matriz de confusão** mostrou que o modelo consegue identificar corretamente a maioria das mensagens, com poucos erros de classificação.
- As **WordClouds** ajudaram a visualizar padrões linguísticos distintos entre mensagens spam e não spam.

---

## 🧠 Aprendizados

Durante o desenvolvimento do projeto, foram aplicados conceitos importantes de NLP e Machine Learning, como:

- Pré-processamento de texto (limpeza e normalização)
- Vetorização com TF-IDF
- Modelos supervisionados de classificação
- Avaliação de desempenho com métricas estatísticas
- Otimização de hiperparâmetros com GridSearchCV

---

## 🚀 Considerações finais

Este projeto demonstra como técnicas de Machine Learning podem ser aplicadas de forma eficiente para resolver problemas reais de classificação de texto.

Além disso, evidencia a importância do pré-processamento e da escolha adequada de modelos para obter bons resultados em tarefas de NLP.

Como possíveis melhorias futuras, podem ser exploradas abordagens mais avançadas, como **modelos baseados em Deep Learning (LSTM, BERT)** e técnicas mais sofisticadas de representação de texto.
"""