# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kiN-hjtcSG-xBNSg2YNEFJ9KZhdnSmiP

#Desafio de Clusterização - K-means (Customer Segmentation)

Automatically generated by Colab.

## Desafio de Clusterização com K-means

## Atividade Avaliativa

### Membros

Edson Maciel e Barros Junior - 20210010250


Neste desafio, aplicamos o algoritmo de **K-means** para um problema de agrupamento.

O objetivo é segmentar clientes com base em suas características, identificando padrões de comportamento.

Esse problema representa um caso de **aprendizado não supervisionado (clustering)**.

## 📌 Etapas:
- Normalização dos dados
- Aplicação do K-means
- Análise dos centróides
- Visualização dos resultados

## 🎯 Saída:
- Grupos de clientes com perfis semelhantes
"""

# ==============================
# IMPORTAÇÃO DAS BIBLIOTECAS
# ==============================

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler

# ==============================
# CARREGAMENTO DE DADOS
# ==============================

# Dataset do Kaggle (faça upload no Colab)
df = pd.read_csv("/content/segmentation data.csv")

# Visualizando dados
df.head()

# ==============================
# ANÁLISE INICIAL
# ==============================

df.info()
df.describe()

# ==============================
# PRÉ-PROCESSAMENTO
# ==============================

# Selecionar apenas colunas numéricas
df_numeric = df.select_dtypes(include=[np.number])

print("Colunas utilizadas:")
print(df_numeric.columns)

# ==============================
# NORMALIZAÇÃO
# ==============================

scaler = StandardScaler()
X_scaled = scaler.fit_transform(df_numeric)

# ==============================
# MÉTODO DO COTOVELO
# ==============================

inertia = []

for k in range(1, 11):
    modelo = KMeans(n_clusters=k, random_state=42)
    modelo.fit(X_scaled)
    inertia.append(modelo.inertia_)

plt.figure()
plt.plot(range(1, 11), inertia)
plt.title("Método do Cotovelo")
plt.xlabel("Número de Clusters")
plt.ylabel("Inertia")
plt.show()

# ==============================
# TREINAMENTO DO MODELO
# ==============================

k = 4  # escolha baseada no gráfico

modelo = KMeans(n_clusters=k, random_state=42)
clusters = modelo.fit_predict(X_scaled)

# Adicionando ao dataframe
df["Cluster"] = clusters

# ==============================
# ANÁLISE DOS CENTRÓIDES
# ==============================

# Voltando para escala original
centroids = scaler.inverse_transform(modelo.cluster_centers_)

centroids_df = pd.DataFrame(centroids, columns=df_numeric.columns)

print("Centróides:")
print(centroids_df)

# ==============================
# GRÁFICO DE BARRAS DOS CENTRÓIDES (VERSÃO MELHORADA)
# ==============================

plt.figure(figsize=(14,7))

# Plot
ax = centroids_df.plot(
    kind='bar',
    width=0.8
)

# Título e labels
plt.title("Perfil dos Clusters (Centróides)", fontsize=16, fontweight='bold')
plt.xlabel("Cluster", fontsize=12)
plt.ylabel("Valores Médios dos Atributos", fontsize=12)

# Melhorar rotação dos rótulos
plt.xticks(rotation=0)

# Legenda organizada
plt.legend(
    title="Atributos",
    bbox_to_anchor=(1.05, 1),
    loc='upper left'
)

# Grid para leitura melhor
plt.grid(axis='y', linestyle='--', alpha=0.7)

# Ajuste automático de layout
plt.tight_layout()

plt.show()

# ==============================
# HEATMAP (DIFERENCIAL)
# ==============================

plt.figure(figsize=(10,6))
sns.heatmap(centroids_df, annot=True, cmap="coolwarm")

plt.title("Heatmap dos Centróides")
plt.show()

# ==============================
# VISUALIZAÇÃO DOS CLUSTERS (2D) - MELHORADA
# ==============================

plt.figure(figsize=(10,6))

# Scatter dos pontos
scatter = plt.scatter(
    df_numeric.iloc[:, 0],
    df_numeric.iloc[:, 1],
    c=clusters,
    cmap='viridis',
    alpha=0.7,
    edgecolor='k'
)

# Plotar centróides
centroids_2d = modelo.cluster_centers_

plt.scatter(
    centroids_2d[:, 0],
    centroids_2d[:, 1],
    c='red',
    s=200,
    marker='X',
    label='Centróides'
)

# Título e labels
plt.title("Clusters de Clientes (Visualização 2D)", fontsize=14, fontweight='bold')
plt.xlabel(df_numeric.columns[0])
plt.ylabel(df_numeric.columns[1])

# Legenda
plt.legend()

# Barra de cores (mostra clusters)
plt.colorbar(scatter, label='Cluster')

# Grid leve
plt.grid(alpha=0.3)

plt.tight_layout()
plt.show()

# ==============================
# INTERPRETAÇÃO DOS CLUSTERS
# ==============================

for i in range(k):
    print(f"\nCluster {i}:")
    print(centroids_df.iloc[i])

# ==============================
# TESTE: NOVO CLIENTE
# ==============================

novo_cliente = df_numeric.iloc[0].values.reshape(1, -1)

novo_cliente_scaled = scaler.transform(novo_cliente)

cluster_previsto = modelo.predict(novo_cliente_scaled)

print(f"Cluster previsto para o cliente: {cluster_previsto[0]}")

"""## Conclusão

O algoritmo K-means permitiu agrupar os clientes em diferentes segmentos com base em suas características.

A normalização foi essencial para garantir que todos os atributos contribuíssem de forma equilibrada no cálculo das distâncias.

Os centróides representam o perfil médio de cada grupo, permitindo interpretar os padrões de comportamento dos clientes.

A visualização por gráfico de barras e heatmap facilitou a comparação entre os clusters.

Essa atividade reforça os conceitos de aprendizado não supervisionado e análise exploratória de dados.
"""