# -*- coding: utf-8 -*-
"""treinar-uma-deep-MLP

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1z69hLj9jqzNYL-p5peOck4E1_1WLcffL

#MLP - CANCER CLASSIFICATION

## Atividade Avaliativa

### Membros

Edson Macield e Barros Junior - 20210010250

Neste desafio, aplicamos o algoritmo de **Rede Neural MLP (Multi-Layer Perceptron)**
para um problema de classificação.

O objetivo é classificar tumores como **malignos ou benignos** com base em características celulares.

Esse problema é um exemplo clássico de **aprendizado supervisionado (classificação)**.

## 📌 Atributos utilizados:
- Características do núcleo celular (raio, textura, perímetro, área, etc.)

## 🎯 Saída:
- Diagnóstico (Maligno ou Benigno)
"""

# ==============================
# IMPORTAÇÃO DAS BIBLIOTECAS
# ==============================

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.impute import SimpleImputer

import seaborn as sns

# ==============================
# CARREGAMENTO DE DADOS
# ==============================

data = load_breast_cancer()

df = pd.DataFrame(data.data, columns=data.feature_names)
df['classe'] = data.target

df.head()

# ==============================
# ANÁLISE INICIAL
# ==============================

df.info()
df.describe()

print(df.columns)

# ==============================
# TRATAMENTO DOS DADOS
# ==============================

# Convertendo saída para nomes mais interpretáveis
df['classe'] = df['classe'].map({0: 'maligno', 1: 'benigno'})

# ==============================
# SEPARAÇÃO DOS DADOS
# ==============================

imputer = SimpleImputer(strategy='mean')

X = df.drop(columns=['classe'])
y = df['classe']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

X = imputer.fit_transform(X)
# ==============================
# NORMALIZAÇÃO (ESSENCIAL PARA MLP)
# ==============================

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# ==============================
# TREINAMENTO DA MLP
# ==============================

modelo = MLPClassifier(
    hidden_layer_sizes=(16, 8),
    activation='relu',
    solver='adam',
    max_iter=1000,
    random_state=42
)

modelo.fit(X_train, y_train)

# ==============================
# AVALIAÇÃO
# ==============================

y_pred = modelo.predict(X_test)

acc = accuracy_score(y_test, y_pred)
print(f"Acurácia: {acc:.4f}")

print("\nRelatório:")
print(classification_report(y_test, y_pred))

# ==============================
# MATRIZ DE CONFUSÃO
# ==============================

cm = confusion_matrix(y_test, y_pred)

plt.figure()
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues')

plt.title("Matriz de Confusão")
plt.xlabel("Predito")
plt.ylabel("Real")

plt.show()

# ==============================
# DISTRIBUIÇÃO DAS CLASSES
# ==============================

plt.figure()

df['classe'].value_counts().plot(kind='bar')

plt.title("Distribuição das Classes")
plt.xlabel("Classe")
plt.ylabel("Quantidade")

plt.show()

# ==============================
# CURVA DE APRENDIZADO (LOSS)
# ==============================

plt.figure()

plt.plot(modelo.loss_curve_)

plt.title("Curva de Perda (Loss)")
plt.xlabel("Épocas")
plt.ylabel("Loss")

plt.show()

# ==============================
# TESTE DE DIFERENTES ARQUITETURAS
# ==============================

arquiteturas = [(8,), (16,), (16,8), (32,16)]
acuracias = []

for arq in arquiteturas:
    modelo_temp = MLPClassifier(hidden_layer_sizes=arq, max_iter=1000)
    modelo_temp.fit(X_train, y_train)

    y_pred_temp = modelo_temp.predict(X_test)
    acc_temp = accuracy_score(y_test, y_pred_temp)

    acuracias.append(acc_temp)

plt.figure()
plt.plot([str(a) for a in arquiteturas], acuracias)

plt.title("Acurácia vs Arquitetura")
plt.xlabel("Arquitetura")
plt.ylabel("Acurácia")

plt.show()

# ==============================
# TESTE DE TAXA DE APRENDIZADO
# ==============================

learning_rates = [0.0001, 0.001, 0.01]
acuracias_lr = []

for lr in learning_rates:
    modelo_temp = MLPClassifier(
        hidden_layer_sizes=(16,8),
        learning_rate_init=lr,
        max_iter=1000
    )

    modelo_temp.fit(X_train, y_train)
    y_pred_temp = modelo_temp.predict(X_test)

    acc_temp = accuracy_score(y_test, y_pred_temp)
    acuracias_lr.append(acc_temp)

plt.figure()
plt.plot(learning_rates, acuracias_lr)

plt.title("Acurácia vs Learning Rate")
plt.xlabel("Learning Rate")
plt.ylabel("Acurácia")

plt.show()

# ==============================
# COMPARAÇÃO COM RANDOM FOREST
# ==============================

from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(n_estimators=100)
rf.fit(X_train, y_train)

y_pred_rf = rf.predict(X_test)

print("Acurácia Random Forest:", accuracy_score(y_test, y_pred_rf))

# ==============================
# CORRELAÇÃO ENTRE VARIÁVEIS
# ==============================

plt.figure(figsize=(10,6))
corr = pd.DataFrame(X).corr()

sns.heatmap(corr, cmap='coolwarm')

plt.title("Matriz de Correlação")

plt.show()

# ==============================
# BOXPLOT (OUTLIERS)
# ==============================

X = imputer.fit_transform(X)

# 🔥 recuperar nomes das colunas
X = pd.DataFrame(X, columns=df.drop(columns=['classe']).columns)

plt.figure(figsize=(10,5))

sns.boxplot(data=pd.DataFrame(X)[['mean radius', 'mean texture', 'mean area']])

plt.title("Boxplot das Variáveis")

plt.show()

"""## Conclusão

A Rede Neural MLP apresentou excelente desempenho na classificação de tumores como malignos ou benignos.

A normalização dos dados foi essencial para o bom funcionamento da rede neural.

A escolha da arquitetura impactou diretamente a acurácia, mostrando a importância do ajuste de hiperparâmetros.

A análise da curva de perda mostrou a convergência do modelo ao longo das épocas.

Comparado ao Random Forest, o modelo MLP apresentou desempenho competitivo, sendo uma alternativa eficiente para problemas de classificação.

"""