# -*- coding: utf-8 -*-
"""Aprendizado_De_Maquina-Final

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Nzp75wc8sAouE3MMMKhHyduedTiP-Nx9

#👶📊 **PreEpi — Análise Exploratória de Dados em Prematuros (2014–2022)**

## 📥 1) Carregamento e visão inicial da base
"""

!pip install lifelines scikit-survival

# =========================
# 0 -  Bibliotecas
# =========================



import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os
import random

from lifelines import KaplanMeierFitter
from lifelines.statistics import logrank_test
from lifelines import CoxPHFitter
from sklearn.preprocessing import StandardScaler
from statsmodels.stats.outliers_influence import variance_inflation_factor
from sklearn.model_selection import train_test_split
from sksurv.util import Surv
from sksurv.ensemble import RandomSurvivalForest
from sksurv.metrics import concordance_index_censored
from sklearn.inspection import permutation_importance
from google.colab import files

plt.style.use('ggplot')
sns.set_theme(style='whitegrid', font_scale=1.1)
plt.rcParams['figure.figsize'] = (10, 5)
plt.rcParams['axes.titlesize'] = 16
plt.rcParams['axes.labelsize'] = 12

# =========================
# 1.0 - Carregamento
# =========================

# abrir seletor de arquivo
uploaded = files.upload()

# pegar nome do arquivo enviado
arquivo = list(uploaded.keys())[0]

# leitura automática
if arquivo.endswith('.parquet'):
    df = pd.read_parquet(arquivo)

elif arquivo.endswith('.csv'):
    df = pd.read_csv(arquivo)

else:
    raise ValueError('Formato não suportado. Envie .parquet ou .csv')

# =========================
# BASE RAW (IMPORTANTE PARA REPRODUTIBILIDADE)
# =========================

df_raw = df.copy()

# Inspeção inicial
print('Dimensão:', df_raw.shape)
display(df_raw.head())

print('------------------------------------------')

# taxa geral de óbito
if 'Obito' in df_raw.columns:
    taxa_obito = df_raw['Obito'].mean() * 100
    print(f'Taxa geral de óbito: {taxa_obito:.2f}%')

df_raw['ANO'].value_counts().sort_index()

# =========================
# 1.1 - Visão geral dos dados
# =========================

info_df = pd.DataFrame({
    "Tipo": df_raw.dtypes,
    "Não nulos": df_raw.count(),
    "Nulos": df_raw.isnull().sum(),
    "% Nulos": (df_raw.isnull().mean() * 100).round(2)
}).sort_values("% Nulos", ascending=False)

display(info_df.head(20))

# =========================
# 1.2 - Função central de modelagem (corrigida)
# =========================

def get_col(df, candidates):
    col = next((c for c in candidates if c in df.columns), None)
    if col is None:
        raise ValueError(f"Nenhuma coluna encontrada entre: {candidates}")
    return col
def preparar_base_modelagem(df, features=None, tempo_max=4):
    df = df.copy()

    # localizar coluna de tempo
    tempo_col = get_col(
        df,
        ['IDADE_OBITO', 'IDADE_OBITO_DIAS', 'DIAS_VIDA']
    )

    if 'Obito' not in df.columns:
        raise ValueError("Coluna 'Obito' não encontrada")

    # criar tempo e evento
    df['tempo_obito'] = pd.to_numeric(df[tempo_col], errors='coerce') / 7
    df['evento'] = pd.to_numeric(df['Obito'], errors='coerce')

    # limpeza
    df = df.dropna(subset=['tempo_obito', 'evento'])
    df = df[df['tempo_obito'] > 0]

    # censura administrativa
    df['evento'] = np.where(df['tempo_obito'] > tempo_max, 0, df['evento'])
    df['tempo_obito'] = np.minimum(df['tempo_obito'], tempo_max)

    # features padrão
    if features is None:
        features = ['IDADEMAE', 'PESO', 'SEMAGESTAC', 'APGAR1', 'APGAR5']

    features = [c for c in features if c in df.columns]

    model_data = df[['tempo_obito', 'evento'] + features].copy()
    model_data = model_data.apply(pd.to_numeric, errors='coerce')

    model_data = model_data.fillna(model_data.median(numeric_only=True))
    model_data = model_data.dropna()

    print("✅ Base preparada:", model_data.shape)

    return model_data

def limpar_evento(df, col='Obito'):
    df = df.copy()

    if col not in df.columns:
        raise ValueError("Coluna Obito não existe")

    # converter tudo para string primeiro
    df[col] = df[col].astype(str).str.strip().str.lower()

    mapa = {
        '1': 1,
        '0': 0,
        'true': 1,
        'false': 0,
        'sim': 1,
        'não': 0,
        'nao': 0
    }

    df[col] = df[col].map(mapa)

    # garantir numérico
    df[col] = pd.to_numeric(df[col], errors='coerce')

    # remover inválidos
    df = df.dropna(subset=[col])

    # forçar inteiro binário
    df[col] = df[col].astype(int)

    return df


np.random.seed(42)
random.seed(42)

"""## ⚰️ 2) Padrões Epidemiológicos e Análise dos Desfechos

"""

# =========================
# 2.0 - Distribuição percentual do desfecho de óbito.
# =========================

if 'Obito' in df.columns:
    dist = df['Obito'].value_counts(normalize=True).mul(100)

    plt.figure(figsize=(8,5))
    ax = sns.barplot(x=dist.index, y=dist.values)

    for i, v in enumerate(dist.values):
        ax.text(i, v + 0.5, f'{v:.1f}%', ha='center')

    plt.title('Distribuição Percentual do Desfecho')
    plt.xlabel('Óbito')
    plt.ylabel('Percentual (%)')
    plt.tight_layout()
    plt.show()

# =========================
# 2.1 - Peso ao nascer
# =========================

#Um dos fatores prognósticos mais importantes em prematuridade.

peso_col = None
for col in ['PESO', 'peso', 'PESOAO_NASCER', 'peso_nascimento']:
    if col in df.columns:
        peso_col = col
        break

if peso_col:
    media_peso = df[peso_col].mean()

    plt.figure(figsize=(10, 5))
    sns.histplot(df[peso_col].dropna(), bins=40, kde=True)

    # Linha da média
    plt.axvline(media_peso, linestyle='--', linewidth=2)
    plt.text(
        media_peso + 50,
        plt.ylim()[1] * 0.9,
        f'Média: {media_peso:.0f} g'
    )

    plt.title('Distribuição do Peso ao Nascer')
    plt.xlabel('Peso (g)')
    plt.ylabel('Frequência')
    plt.tight_layout()
    plt.show()

# =========================
# 2.2 - Mortalidade por faixa de peso
# =========================

if peso_col and 'Obito' in df.columns:

    bins = [0, 1000, 1500, 2500, 6000]

    labels = [
        '<1000g',
        '1000–1499g',
        '1500–2499g',
        '≥2500g'
    ]

    # cópia segura
    df_temp = df.copy()

    # criar faixas de peso
    df_temp['faixa_peso'] = pd.cut(
        df_temp[peso_col],
        bins=bins,
        labels=labels,
        include_lowest=True
    )

    # mortalidade por grupo
    mort_peso = (
        df_temp
        .groupby('faixa_peso', observed=False)['Obito']
        .mean()
        .mul(100)
        .reindex(labels)
    )

    # gráfico
    plt.figure(figsize=(10, 5))

    ax = mort_peso.plot(kind='bar')

    ax.bar_label(
        ax.containers[0],
        fmt='%.1f%%'
    )

    plt.title('Taxa de Óbito por Faixa de Peso')

    plt.ylabel('Taxa de óbito (%)')
    plt.xlabel('Faixa de peso')

    plt.xticks(rotation=0)

    plt.grid(axis='y', alpha=0.3)

    plt.tight_layout()
    plt.show()

# Espera-se maior mortalidade nas faixas de muito baixo peso,
# especialmente abaixo de 1000g.

# =========================
# 2.3 - Apgar 5 vs óbito
# =========================

# Comparação do estado clínico neonatal com o desfecho.

apgar_col = None
for col in ['APGAR5', 'apgar5']:
    if col in df.columns:
        apgar_col = col
        break

if apgar_col and 'Obito' in df.columns:
    plt.figure(figsize=(10,5))
    sns.boxplot(data=df, x='Obito', y=apgar_col)
    plt.title('Apgar no 5º minuto vs Óbito')
    plt.xlabel('Óbito')
    plt.ylabel('Apgar 5')
    plt.tight_layout()
    plt.show()

# Apgar é uma nota clínica dada ao bebê logo após o nascimento.

# =========================
# 2.4 - Mortalidade por raça/cor
# =========================

# Investigação inicial de possíveis desigualdades.

raca_col = None
for col in ['RACACORMAE', 'racacormae']:
    if col in df.columns:
        raca_col = col
        break

if raca_col and 'Obito' in df.columns:
    mapa_raca = {
        1: 'Branca',
        2: 'Preta',
        3: 'Amarela',
        4: 'Parda',
        5: 'Indígena'
    }

    df['raca_nome'] = df[raca_col].map(mapa_raca)
    mort_raca = (
        df.groupby('raca_nome')['Obito']
        .mean()
        .mul(1000)
        .sort_values(ascending=False)
    )

    plt.figure(figsize=(10, 5))
    ax = sns.barplot(
        x=mort_raca.index,
        y=mort_raca.values
    )

    for i, v in enumerate(mort_raca.values):
        ax.text(i, v + 1, f'{v:.1f}', ha='center')

    plt.title('Taxa de Mortalidade por 1000\nRaça/Cor da Mãe')
    plt.ylabel('Óbitos por 1000')
    plt.xlabel('Raça/Cor')
    plt.xticks(rotation=20)
    plt.grid(axis='y', alpha=0.3)
    plt.tight_layout()
    plt.show()

# =========================
# 2.5 - Tendência temporal
# =========================

# Evolução anual com destaque para a COVID-19.

ano_col = None
for col in ['ANO', 'ano']:
    if col in df.columns:
        ano_col = col
        break

if ano_col and 'Obito' in df.columns:

    # Criar a série temporal (óbitos por ano)
    ts = df.groupby(ano_col)['Obito'].sum().sort_index()

    # Média móvel
    ts_mm = ts.rolling(window=2).mean()

    plt.figure(figsize=(12,5))
    plt.plot(ts.index, ts.values, marker='o', label='Original')
    plt.plot(ts_mm.index, ts_mm.values, linestyle='--', label='Média móvel')

    # Destaque para início da COVID-19
    plt.axvline(2020, linestyle='--', color='red', label='Início COVID-19')

    plt.title('Tendência Temporal da Mortalidade Neonatal')
    plt.xlabel('Ano')
    plt.ylabel('Número de Óbitos')
    plt.legend()
    plt.tight_layout()
    plt.show()

# =========================
# 2.6 - Heatmap de correlação
# =========================

# Selecionar variáveis existentes
cols_interesse = [
    col for col in [
        'IDADEMAE',
        'PESO',
        'SEMAGESTAC',
        'APGAR1',
        'APGAR5',
        'Obito'
    ]
    if col in df.columns
]

# Correlação
if len(cols_interesse) > 2:

    # selecionar apenas numéricas
    corr_df = df[cols_interesse].apply(
        pd.to_numeric,
        errors='coerce'
    )

    # matriz de correlação
    corr = corr_df.corr()

    # heatmap
    plt.figure(figsize=(10, 6))

    sns.heatmap(
        corr,
        annot=True,
        fmt='.2f',
        cmap='coolwarm',
        center=0,
        linewidths=0.5,
        square=True
    )

    plt.title(
        'Correlação entre Variáveis Clínicas Principais'
    )

    plt.tight_layout()
    plt.show()

    # Correlação com óbito
    if 'Obito' in corr.columns:

        corr_evento = (
            corr['Obito']
            .sort_values(ascending=False)
        )

        print("\n📊 Correlação com Óbito:\n")
        print(corr_evento)

"""## 📋 3) Preparar variável tempo-até-óbito"""

# =========================
# 3.1 — Criar df_surv
# =========================

# features principais
features = [
    'IDADEMAE',
    'PESO',
    'SEMAGESTAC',
    'APGAR1',
    'APGAR5'
]

# manter apenas colunas existentes
features = [
    c for c in features
    if c in df.columns
]

print("📌 Features utilizadas:")
print(features)

# criar base sobrevivência
df_surv = preparar_base_modelagem(
    df,
    features=features,
    tempo_max=4
)

# base final para modelagem
model_data = df_surv.copy()

# conferência
print("📊 N:", len(df_surv))
print("⚰️ Eventos:", df_surv['evento'].sum())

sns.set(style="whitegrid", font_scale=1.2)

print('---------------------------------------------------------------')


# Histograma

g = sns.displot(
    data=df_surv,
    x="tempo_obito",
    col="evento",
    bins=30,
    kde=True,
    height=5,
    aspect=1
)

g.set_titles(col_template="Evento = {col_name}")
g.set_axis_labels("Tempo (semanas)", "Frequência")

plt.suptitle(
    "Distribuição do Tempo até Evento",
    y=1.05
)

plt.show()

# =========================
# 3.2 — Visualizações
# =========================

kmf = KaplanMeierFitter()

plt.figure()

kmf.fit(
    df_surv['tempo_obito'],
    df_surv['evento']
)

kmf.plot(ci_show=True)

mediana = kmf.median_survival_time_

plt.axhline(0.5, linestyle='--')
plt.axvline(mediana, linestyle='--')

plt.title('Curva de Sobrevivência (Kaplan-Meier)')
plt.xlabel('Tempo (semanas)')
plt.ylabel('Probabilidade de Sobrevivência')

plt.text(mediana, 0.52, f'Mediana ≈ {mediana:.2f}')

plt.grid(alpha=0.3)
plt.show()

# =========================
# 3.3 — KAPLAN-MEIER geral
# =========================

# Violin + box
plt.figure()

sns.violinplot(
    data=df_surv,
    x="evento",
    y="tempo_obito",
    inner="box"
)

plt.title("Distribuição do Tempo até Evento por Desfecho")
plt.xlabel("Evento (0 = censurado, 1 = óbito)")
plt.ylabel("Tempo (semanas)")
plt.show()

# =========================
# 3.4 — KM por peso
# =========================

if 'PESO' in df_raw.columns:

    bins = [0, 1000, 1500, 2500, 6000]
    labels = ['<1000g', '1000–1499g', '1500–2499g', '≥2500g']

    # alinhar corretamente com df_surv
    df_surv_aligned = df_surv.copy()

    # reconstruir PESO no mesmo índice do df_surv
    df_surv_aligned = df_surv.copy()
    df_surv_aligned = df_surv_aligned.reset_index(drop=True)
    df_raw_aligned = df_raw.reset_index(drop=True)
    df_surv_aligned['PESO'] = df_raw_aligned['PESO']

    # 🔴 AQUI estava faltando: criar a faixa de peso
    df_surv_aligned['faixa_peso'] = pd.cut(
        df_surv_aligned['PESO'],
        bins=bins,
        labels=labels,
        include_lowest=True
    )

    plt.figure()

    for grupo in labels:
        sub = df_surv_aligned[df_surv_aligned['faixa_peso'] == grupo]

        if len(sub) > 10:  # (50 é muito rígido; pode quebrar análise)
            kmf.fit(
                durations=sub['tempo_obito'],
                event_observed=sub['evento'],
                label=f"{grupo} (n={len(sub)})"
            )
            kmf.plot(ci_show=False)

    plt.title('Sobrevivência por Faixa de Peso')
    plt.xlabel('Tempo (semanas)')
    plt.ylabel('Probabilidade de Sobrevivência')

    plt.legend(title='Faixa de peso')
    plt.grid(alpha=0.3)
    plt.show()

"""## ⚰️ 4) Curvas Kaplan-Meier estratificadas"""

# =========================
# 4.0 - Kaplan-Meier Global
# =========================

kmf = KaplanMeierFitter()

kmf.fit(
    durations=df_surv['tempo_obito'],
    event_observed=df_surv['evento'],
    label="Geral"
)

plt.figure(figsize=(8,5))
ax = kmf.plot(ci_show=True)

mediana = kmf.median_survival_time_

plt.axhline(0.5, linestyle='--', alpha=0.5)
plt.axvline(mediana, linestyle='--', alpha=0.5)

plt.title("Curva de Kaplan-Meier — Geral")
plt.xlabel("Tempo (semanas)")
plt.ylabel("Probabilidade de Sobrevivência")

plt.text(mediana, 0.52, f"Mediana ≈ {mediana:.2f}")

plt.grid(alpha=0.3)
plt.show()

# =========================
# 4.1 - KM por Faixa de Peso
# =========================

bins = [0, 1000, 1500, 2500, 6000]
labels = ['<1000g', '1000–1499g', '1500–2499g', '≥2500g']

df_surv = df_surv.copy()

df_surv['faixa_peso'] = pd.cut(
    df.loc[df_surv.index, 'PESO'],
    bins=bins,
    labels=labels,
    include_lowest=True
)

plt.figure(figsize=(9,5))

kmf = KaplanMeierFitter()

for grupo in labels:

    sub = df_surv[df_surv['faixa_peso'] == grupo]

    if len(sub) > 10:
        kmf.fit(
            durations=sub['tempo_obito'],
            event_observed=sub['evento'],
            label=f"{grupo} (n={len(sub)})"
        )
        kmf.plot(ci_show=False)

plt.title("Kaplan-Meier por Faixa de Peso")
plt.xlabel("Tempo (semanas)")
plt.ylabel("Probabilidade de Sobrevivência")
plt.grid(alpha=0.3)
plt.legend()
plt.show()

# =========================
# 4.2 - KM por Idade Gestacional
# =========================

# alinhar índices
df_surv = df_surv.reset_index(drop=True)
df = df.reset_index(drop=True)

# mapa SINASC
mapa_ig = {
    1: 'Extremo (<22)',
    2: 'Muito prematuro (22–27)',
    3: 'Prematuro (28–31)',
    4: 'Moderado (32–36)',
    5: 'Termo (37–41)',
    6: 'Pós-termo (42+)',
}

# converter
df_surv['faixa_ig'] = (
    pd.to_numeric(df['SEMAGESTAC'], errors='coerce')
    .map(mapa_ig)
)

print(df_surv['faixa_ig'].value_counts(dropna=False))

plt.figure(figsize=(10,6))

kmf = KaplanMeierFitter()

for grupo in df_surv['faixa_ig'].dropna().unique():

    sub = df_surv[df_surv['faixa_ig'] == grupo]

    print(f"{grupo}: {len(sub)}")

    if len(sub) > 10:

        kmf.fit(
            durations=sub['tempo_obito'],
            event_observed=sub['evento'],
            label=f"{grupo} (n={len(sub)})"
        )

        kmf.plot(ci_show=False)

plt.title("Kaplan-Meier por Idade Gestacional")
plt.xlabel("Tempo (semanas)")
plt.ylabel("Probabilidade de Sobrevivência")
plt.grid(alpha=0.3)
plt.legend()
plt.show()

# =========================
# 4.3 - KM por Região
# =========================

reg_col = get_col(df_raw, ['REGIAO', 'nasc_REGIAO', 'res_REGIAO'])

if reg_col:

    # alinhar índices
    df_surv = df_surv.reset_index(drop=True)
    df_raw = df_raw.reset_index(drop=True)

    # região já vem como texto
    df_surv['regiao'] = df_raw[reg_col]

    print(df_surv['regiao'].value_counts())

    plt.figure(figsize=(10,6))

    kmf = KaplanMeierFitter()

    for r in df_surv['regiao'].dropna().unique():

        sub = df_surv[df_surv['regiao'] == r]

        if len(sub) > 5:

            kmf.fit(
                durations=sub['tempo_obito'],
                event_observed=sub['evento'],
                label=f"{r} (n={len(sub)})"
            )

            kmf.plot(ci_show=False)

    plt.title("Kaplan-Meier por Região")
    plt.xlabel("Tempo (semanas)")
    plt.ylabel("Probabilidade de Sobrevivência")
    plt.grid(alpha=0.3)
    plt.legend()
    plt.show()

# =========================
# 4.5 - LOG-RANK TEST ENTRE GRUPOS
# =========================

def logrank_pairwise(df_input, group_col):

    # cópia segura
    df_temp = df_input.copy()

    # verificar coluna
    if group_col not in df_temp.columns:

        print(f"❌ Coluna '{group_col}' não encontrada.")
        return pd.DataFrame()

    # remover nulos
    df_temp = df_temp.dropna(
        subset=['tempo_obito', 'evento', group_col]
    )

    # grupos válidos
    groups = sorted(
        df_temp[group_col].unique()
    )

    results = []

    # comparações
    for i in range(len(groups)):

        for j in range(i + 1, len(groups)):

            g1 = groups[i]
            g2 = groups[j]

            d1 = df_temp[
                df_temp[group_col] == g1
            ]

            d2 = df_temp[
                df_temp[group_col] == g2
            ]

            # evitar grupos muito pequenos
            if len(d1) < 2 or len(d2) < 2:
                continue

            # log-rank
            res = logrank_test(
                d1['tempo_obito'],
                d2['tempo_obito'],
                event_observed_A=d1['evento'],
                event_observed_B=d2['evento']
            )

            results.append({
                'Grupo A': g1,
                'Grupo B': g2,
                'p-value': res.p_value
            })

    return pd.DataFrame(results)


# FUNÇÃO HEATMAP

def plot_logrank_heatmap(df_input, group_col, title):

    # verificar coluna
    if group_col not in df_input.columns:

        print(f"❌ Coluna '{group_col}' não encontrada.")
        return

    # executar log-rank
    res = logrank_pairwise(
        df_input,
        group_col
    )

    # verificar vazio
    if res.empty:

        print(f"⚠️ Nenhum resultado válido para {title}")
        return

    # grupos
    groups = sorted(
        df_input[group_col]
        .dropna()
        .unique()
    )

    # matriz
    mat = pd.DataFrame(
        np.ones((len(groups), len(groups))),
        index=groups,
        columns=groups
    )

    # diagonal
    np.fill_diagonal(mat.values, 0)

    # preencher
    for _, row in res.iterrows():

        g1 = row['Grupo A']
        g2 = row['Grupo B']
        p = row['p-value']

        mat.loc[g1, g2] = p
        mat.loc[g2, g1] = p

    # escala log
    mat_plot = -np.log10(mat + 1e-300)

    # plot
    plt.figure(figsize=(8,6))

    sns.heatmap(
        mat_plot,
        annot=mat,
        fmt='.2e',
        cmap='viridis',
        linewidths=0.5
    )

    plt.title(
        f'Log-rank Test — {title} (-log10 p-value)'
    )

    plt.tight_layout()
    plt.show()

# 📊 PESO

print("\n⚰️ LOG-RANK TEST - PESO")

df_surv_peso = df_surv.copy()

df_surv_peso['faixa_peso'] = pd.cut(
    df_surv_peso['PESO'],
    bins=[0, 1000, 1500, 2500, 6000],
    labels=['<1000', '1000-1499', '1500-2499', '≥2500'],
    include_lowest=True
)

print("\n📊 Distribuição:")
print(df_surv_peso['faixa_peso'].value_counts(dropna=False))

df_surv_peso = df_surv_peso.dropna(subset=['faixa_peso'])

if df_surv_peso['faixa_peso'].nunique() < 2:
    print("⚠️ Apenas 1 grupo")
else:
    plot_logrank_heatmap(df_surv_peso, 'faixa_peso', 'Peso')

# 📊 IDADE GESTACIONAL

print("\n⚰️ LOG-RANK TEST - IG")

df_surv_ig = df_surv.copy()

# ✔️ CORRETO: variável é categórica codificada (2–5)
map_ig = {
    2: "<28",
    3: "28-31",
    4: "32-36",
    5: "≥37"
}

df_surv_ig["faixa_ig"] = df_surv_ig["SEMAGESTAC"].map(map_ig)

print("\n📊 Distribuição:")
print(df_surv_ig["faixa_ig"].value_counts(dropna=False))

# remover NaN
df_surv_ig = df_surv_ig.dropna(subset=["faixa_ig"])

# checar número de grupos válidos
if df_surv_ig["faixa_ig"].nunique() < 2:
    print("⚠️ Apenas 1 grupo")
else:
    plot_logrank_heatmap(
        df_surv_ig,
        "faixa_ig",
        "IG"
    )

# 📊 REGIÃO

print("\n⚰️ LOG-RANK TEST - REGIÃO")

df_surv_regiao = df_surv.copy()

reg_col = get_col(df_raw, ['res_REGIAO', 'nasc_REGIAO', 'res_Reg', 'nasc_Reg'])

if reg_col:

    print(f"📌 Coluna: {reg_col}")

    df_surv_regiao['regiao_nome'] = df_raw.loc[df_surv.index, reg_col]

    print("\n📊 Distribuição:")
    print(df_surv_regiao['regiao_nome'].value_counts(dropna=False))

    df_surv_regiao = df_surv_regiao.dropna(subset=['regiao_nome'])

    if df_surv_regiao['regiao_nome'].nunique() < 2:
        print("⚠️ Apenas 1 grupo")
    else:
        plot_logrank_heatmap(df_surv_regiao, 'regiao_nome', 'Região')

else:
    print("❌ Sem coluna de região")

"""## ⚰️ 5) Modelo de Cox"""

# =========================
# 5.0 — Split Reprodutível
# =========================

# features FIXAS (garantir sem variáveis categóricas)
features = ['IDADEMAE', 'PESO', 'SEMAGESTAC', 'APGAR1', 'APGAR5']

# 1. ISOLAR APENAS COLUNAS NECESSÁRIAS
model_data = df_surv[features + ['tempo_obito', 'evento']].copy()

# FORÇAR NUMÉRICO (REMOVE STRINGS OCULTAS)
for col in features + ['tempo_obito', 'evento']:
    model_data[col] = pd.to_numeric(model_data[col], errors='coerce')

# remover qualquer coisa inválida
model_data = model_data.dropna()

# SPLIT (SEM LEAKAGE)
train_df, test_df = train_test_split(
    model_data,
    test_size=0.2,
    random_state=42,
    stratify=model_data['evento']
)

train_df = train_df.copy()
test_df = test_df.copy()

# PADRONIZAÇÃO
scaler = StandardScaler()

train_df.loc[:, features] = scaler.fit_transform(train_df[features])
test_df.loc[:, features] = scaler.transform(test_df[features])

# VIF (GARANTIA ABSOLUTA DE FLOAT PURO)
X_vif = train_df[features].astype(float)
vif = pd.DataFrame()
vif["variavel"] = X_vif.columns
vif["VIF"] = [
    variance_inflation_factor(X_vif.values, i)
    for i in range(X_vif.shape[1])
]

display(vif)

# COX PH MODEL
cph = CoxPHFitter()
cph.fit(
    train_df,
    duration_col='tempo_obito',
    event_col='evento'
)

cph.print_summary()

# =========================
# 5.1 - COX Proportional Hazard Ratios
# =========================

cph = CoxPHFitter()

cph.fit(
    train_df,
    duration_col='tempo_obito',
    event_col='evento'
)

cph.print_summary()

# C-index Cox
cox_cindex = cph.concordance_index_
print("C-index Cox:", cox_cindex)

# Hazard Ratios (interpretável clinicamente)
hr = np.exp(cph.params_).sort_values()
print("\nHazard Ratios:")
print(hr)

plt.figure(figsize=(8,5))
cph.plot()
plt.title("Hazard Ratios — Cox PH")
plt.grid(alpha=0.3)
plt.show()

# =========================
# 5.2 - Check de Suposições
# =========================

cph.check_assumptions(
    train_df,
    p_value_threshold=0.05,
    show_plots=False
)

"""## ⚰️ 6) PCA"""

# =========================================
# 6.0 - PCA (Principal Component Analysis)
# =========================================

from sklearn.decomposition import PCA

print("\n📊 PCA - Redução de Dimensionalidade")

# -------------------------
# Variáveis clínicas
# -------------------------

features_pca = [
    'IDADEMAE',
    'PESO',
    'SEMAGESTAC',
    'APGAR1',
    'APGAR5'
]

features_pca = [
    c for c in features_pca
    if c in df_surv.columns
]

print("Features utilizadas:")
print(features_pca)

# -------------------------
# Base PCA
# -------------------------

X_pca_base = df_surv[features_pca].copy()

X_pca_base = (
    X_pca_base
    .apply(pd.to_numeric, errors='coerce')
)

X_pca_base = (
    X_pca_base
    .fillna(
        X_pca_base.median(
            numeric_only=True
        )
    )
)

# -------------------------
# Padronização
# -------------------------

scaler_pca = StandardScaler()

X_scaled = scaler_pca.fit_transform(
    X_pca_base
)

# -------------------------
# PCA 2 componentes
# -------------------------

pca = PCA(
    n_components=2,
    random_state=42
)

X_pca = pca.fit_transform(
    X_scaled
)

# -------------------------
# DataFrame PCA
# -------------------------

df_pca = pd.DataFrame(
    X_pca,
    columns=['PC1', 'PC2']
)

df_pca['evento'] = (
    df_surv['evento']
    .reset_index(drop=True)
)

# -------------------------
# Variância explicada
# -------------------------

var_exp = (
    pca.explained_variance_ratio_
)

print("\n📈 Variância explicada")

for i, v in enumerate(var_exp):
    print(
        f"PC{i+1}: {v*100:.2f}%"
    )

print(
    f"\nTotal: {var_exp.sum()*100:.2f}%"
)

# -------------------------
# Componentes principais
# -------------------------

loadings = pd.DataFrame(
    pca.components_.T,
    columns=['PC1', 'PC2'],
    index=features_pca
)

print("\n📋 Contribuição das Variáveis")
display(loadings)

# -------------------------
# Scree Plot
# -------------------------

plt.figure(figsize=(8,5))

plt.bar(
    ['PC1', 'PC2'],
    var_exp * 100
)

for i, v in enumerate(var_exp):
    plt.text(
        i,
        v*100 + 1,
        f'{v*100:.1f}%'
    )

plt.title(
    'Variância Explicada pelo PCA'
)

plt.ylabel(
    'Variância (%)'
)

plt.grid(
    axis='y',
    alpha=0.3
)

plt.show()

# -------------------------
# PCA - Óbito vs Sobrevivência
# -------------------------

plt.figure(figsize=(10,6))

sns.scatterplot(
    data=df_pca,
    x='PC1',
    y='PC2',
    hue='evento',
    alpha=0.7
)

plt.title(
    'PCA - Sobreviventes vs Óbitos'
)

plt.xlabel(
    f'PC1 ({var_exp[0]*100:.1f}%)'
)

plt.ylabel(
    f'PC2 ({var_exp[1]*100:.1f}%)'
)

plt.legend(
    title='Evento'
)

plt.grid(alpha=0.3)

plt.show()

# -------------------------
# Correlação dos Componentes
# -------------------------

plt.figure(figsize=(8,5))

sns.heatmap(
    loadings,
    annot=True,
    cmap='coolwarm',
    center=0
)

plt.title(
    'Contribuição das Variáveis para os Componentes'
)

plt.tight_layout()

plt.show()

# -------------------------
# Estatísticas PCA
# -------------------------

print("\n📊 Resumo PCA")

print(
    "Número de observações:",
    len(df_pca)
)

print(
    "Número de variáveis:",
    len(features_pca)
)

print(
    f"Variância total explicada: {var_exp.sum()*100:.2f}%"
)

"""## ⚰️ 7) K-Means"""

# =========================================
# 7.0 - K-MEANS
# =========================================

from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score

print("\n🎯 K-Means - Agrupamento dos Prematuros")

# -------------------------
# Base para clustering
# -------------------------

X_cluster = df_pca[['PC1', 'PC2']]

# -------------------------
# Método do Cotovelo
# -------------------------

inercias = []

for k in range(2, 11):

    km = KMeans(
        n_clusters=k,
        random_state=42,
        n_init=10
    )

    km.fit(X_cluster)

    inercias.append(
        km.inertia_
    )

plt.figure(figsize=(8,5))

plt.plot(
    range(2,11),
    inercias,
    marker='o'
)

plt.title(
    'Método do Cotovelo'
)

plt.xlabel(
    'Número de Clusters'
)

plt.ylabel(
    'Inércia'
)

plt.grid(alpha=0.3)

plt.show()

# -------------------------
# Modelo Final
# -------------------------

kmeans = KMeans(
    n_clusters=3,
    random_state=42,
    n_init=10
)

clusters = kmeans.fit_predict(
    X_cluster
)

df_pca['cluster'] = clusters

# -------------------------
# Silhouette Score
# -------------------------

sil = silhouette_score(
    X_cluster,
    clusters
)

print(
    f"\n📊 Silhouette Score: {sil:.4f}"
)

# -------------------------
# Distribuição dos Clusters
# -------------------------

print("\n📋 Distribuição")

print(
    df_pca['cluster']
    .value_counts()
    .sort_index()
)

# -------------------------
# Visualização PCA + KMeans
# -------------------------

plt.figure(figsize=(10,6))

sns.scatterplot(
    data=df_pca,
    x='PC1',
    y='PC2',
    hue='cluster',
    palette='Set2',
    alpha=0.8
)

plt.scatter(
    kmeans.cluster_centers_[:,0],
    kmeans.cluster_centers_[:,1],
    marker='X',
    s=250,
    color='black',
    label='Centroides'
)

plt.title(
    'Clusters de Prematuros (K-Means)'
)

plt.xlabel('PC1')
plt.ylabel('PC2')

plt.legend()

plt.grid(alpha=0.3)

plt.show()

# -------------------------
# Mortalidade por Cluster
# -------------------------

df_cluster = df_pca.copy()

df_cluster['evento'] = (
    df_surv['evento']
    .reset_index(drop=True)
)

mortalidade = (
    df_cluster
    .groupby('cluster')['evento']
    .mean()
    .mul(100)
    .round(2)
)

print("\n⚰️ Mortalidade por Cluster (%)")

print(mortalidade)

# -------------------------
# Gráfico Mortalidade
# -------------------------

plt.figure(figsize=(8,5))

ax = sns.barplot(
    x=mortalidade.index.astype(str),
    y=mortalidade.values
)

for i, v in enumerate(mortalidade.values):

    ax.text(
        i,
        v + 0.5,
        f'{v:.1f}%',
        ha='center'
    )

plt.title(
    'Taxa de Óbito por Cluster'
)

plt.xlabel(
    'Cluster'
)

plt.ylabel(
    'Mortalidade (%)'
)

plt.grid(
    axis='y',
    alpha=0.3
)

plt.show()

# -------------------------
# Perfil dos Clusters
# -------------------------

features_cluster = [
    c for c in [
        'IDADEMAE',
        'PESO',
        'SEMAGESTAC',
        'APGAR1',
        'APGAR5'
    ]
    if c in df_surv.columns
]

perfil = df_surv.copy()

perfil['cluster'] = clusters

perfil_cluster = (
    perfil
    .groupby('cluster')[features_cluster]
    .mean()
    .round(2)
)

print("\n📊 Perfil Médio dos Clusters")

display(perfil_cluster)

"""## ⚰️ 8) Regressão Logística"""

# =========================================
# 8.0 - REGRESSÃO LOGÍSTICA
# =========================================

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    confusion_matrix,
    classification_report,
    ConfusionMatrixDisplay,
    RocCurveDisplay
)

print("\n🧠 Regressão Logística")

# -------------------------
# Variáveis
# -------------------------

features_ml = [
    'IDADEMAE',
    'PESO',
    'SEMAGESTAC',
    'APGAR1',
    'APGAR5'
]

features_ml = [
    c for c in features_ml
    if c in df_surv.columns
]

# -------------------------
# Base
# -------------------------

X = df_surv[features_ml].copy()

y = df_surv['evento'].copy()

# garantir numérico
X = X.apply(pd.to_numeric, errors='coerce')

# imputação
X = X.fillna(
    X.median(
        numeric_only=True
    )
)

# -------------------------
# Split
# -------------------------

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

# -------------------------
# Padronização
# -------------------------

scaler_lr = StandardScaler()

X_train_scaled = scaler_lr.fit_transform(
    X_train
)

X_test_scaled = scaler_lr.transform(
    X_test
)

# -------------------------
# Modelo
# -------------------------

lr = LogisticRegression(
    random_state=42,
    max_iter=1000
)

lr.fit(
    X_train_scaled,
    y_train
)

# -------------------------
# Predições
# -------------------------

y_pred = lr.predict(
    X_test_scaled
)

y_prob = lr.predict_proba(
    X_test_scaled
)[:,1]

# -------------------------
# Métricas
# -------------------------

acc = accuracy_score(
    y_test,
    y_pred
)

prec = precision_score(
    y_test,
    y_pred,
    zero_division=0
)

rec = recall_score(
    y_test,
    y_pred,
    zero_division=0
)

f1 = f1_score(
    y_test,
    y_pred,
    zero_division=0
)

auc = roc_auc_score(
    y_test,
    y_prob
)

print("\n📊 Métricas")

print(f"Accuracy : {acc:.4f}")
print(f"Precision: {prec:.4f}")
print(f"Recall   : {rec:.4f}")
print(f"F1-score : {f1:.4f}")
print(f"ROC-AUC  : {auc:.4f}")

# -------------------------
# Classification Report
# -------------------------

print("\n📋 Classification Report")

print(
    classification_report(
        y_test,
        y_pred,
        zero_division=0
    )
)

# -------------------------
# Matriz de Confusão
# -------------------------

cm = confusion_matrix(
    y_test,
    y_pred
)

fig, ax = plt.subplots(
    figsize=(6,5)
)

ConfusionMatrixDisplay(
    confusion_matrix=cm
).plot(
    ax=ax,
    colorbar=False
)

plt.title(
    'Regressão Logística - Matriz de Confusão'
)

plt.show()

# -------------------------
# Curva ROC
# -------------------------

fig, ax = plt.subplots(
    figsize=(6,5)
)

RocCurveDisplay.from_predictions(
    y_test,
    y_prob,
    ax=ax
)

plt.title(
    'Regressão Logística - Curva ROC'
)

plt.show()

# -------------------------
# Importância dos Coeficientes
# -------------------------

coeficientes = pd.DataFrame({
    'Variável': features_ml,
    'Coeficiente': lr.coef_[0]
})

coeficientes = coeficientes.sort_values(
    'Coeficiente',
    ascending=False
)

print("\n📈 Coeficientes")

display(coeficientes)

plt.figure(figsize=(8,5))

sns.barplot(
    data=coeficientes,
    x='Coeficiente',
    y='Variável'
)

plt.title(
    'Importância dos Coeficientes'
)

plt.grid(alpha=0.3)

plt.show()

# -------------------------
# Salvar resultados
# -------------------------

resultado_lr = {
    'Modelo': 'Regressão Logística',
    'Accuracy': acc,
    'Precision': prec,
    'Recall': rec,
    'F1': f1,
    'ROC_AUC': auc
}

print("\n✅ Regressão Logística concluída")

"""## ⚰️ 9) Árvore de Decisão"""

# =========================================
# 9.0 - ÁRVORE DE DECISÃO
# =========================================

from sklearn.tree import (
    DecisionTreeClassifier,
    plot_tree
)

print("\n🌳 Árvore de Decisão")

# -------------------------
# Modelo
# -------------------------

tree = DecisionTreeClassifier(
    max_depth=5,
    min_samples_split=20,
    min_samples_leaf=10,
    random_state=42
)

tree.fit(
    X_train,
    y_train
)

# -------------------------
# Predições
# -------------------------

y_pred_tree = tree.predict(
    X_test
)

y_prob_tree = tree.predict_proba(
    X_test
)[:,1]

# -------------------------
# Métricas
# -------------------------

acc_tree = accuracy_score(
    y_test,
    y_pred_tree
)

prec_tree = precision_score(
    y_test,
    y_pred_tree,
    zero_division=0
)

rec_tree = recall_score(
    y_test,
    y_pred_tree,
    zero_division=0
)

f1_tree = f1_score(
    y_test,
    y_pred_tree,
    zero_division=0
)

auc_tree = roc_auc_score(
    y_test,
    y_prob_tree
)

print("\n📊 Métricas")

print(f"Accuracy : {acc_tree:.4f}")
print(f"Precision: {prec_tree:.4f}")
print(f"Recall   : {rec_tree:.4f}")
print(f"F1-score : {f1_tree:.4f}")
print(f"ROC-AUC  : {auc_tree:.4f}")

# -------------------------
# Classification Report
# -------------------------

print("\n📋 Classification Report")

print(
    classification_report(
        y_test,
        y_pred_tree,
        zero_division=0
    )
)

# -------------------------
# Matriz de Confusão
# -------------------------

cm_tree = confusion_matrix(
    y_test,
    y_pred_tree
)

fig, ax = plt.subplots(
    figsize=(6,5)
)

ConfusionMatrixDisplay(
    confusion_matrix=cm_tree
).plot(
    ax=ax,
    colorbar=False
)

plt.title(
    'Árvore de Decisão - Matriz de Confusão'
)

plt.show()

# -------------------------
# Curva ROC
# -------------------------

fig, ax = plt.subplots(
    figsize=(6,5)
)

RocCurveDisplay.from_predictions(
    y_test,
    y_prob_tree,
    ax=ax
)

plt.title(
    'Árvore de Decisão - Curva ROC'
)

plt.show()

# -------------------------
# Importância das Variáveis
# -------------------------

importancias = pd.DataFrame({
    'Variável': features_ml,
    'Importância': tree.feature_importances_
})

importancias = importancias.sort_values(
    'Importância',
    ascending=False
)

print("\n📈 Importância das Variáveis")

display(importancias)

plt.figure(figsize=(8,5))

sns.barplot(
    data=importancias,
    x='Importância',
    y='Variável'
)

plt.title(
    'Importância das Variáveis - Árvore de Decisão'
)

plt.grid(alpha=0.3)

plt.show()

# -------------------------
# Visualização da Árvore
# -------------------------

plt.figure(figsize=(18,10))

plot_tree(
    tree,
    feature_names=features_ml,
    class_names=[
        'Sobreviveu',
        'Óbito'
    ],
    filled=True,
    rounded=True,
    fontsize=8
)

plt.title(
    'Árvore de Decisão'
)

plt.show()

# -------------------------
# Salvar Resultados
# -------------------------

resultado_tree = {
    'Modelo': 'Árvore de Decisão',
    'Accuracy': acc_tree,
    'Precision': prec_tree,
    'Recall': rec_tree,
    'F1': f1_tree,
    'ROC_AUC': auc_tree
}

print("\n✅ Árvore de Decisão concluída")

"""## ⚰️ 10) SVM (Support Vector Machine)

"""

# =========================================
# 10.0 - SVM
# =========================================

from sklearn.svm import SVC

print("\n🔵 Support Vector Machine (SVM)")

# -------------------------
# Modelo
# -------------------------

svm = SVC(
    kernel='rbf',
    C=1.0,
    probability=True,
    random_state=42
)

svm.fit(
    X_train_scaled,
    y_train
)

# -------------------------
# Predições
# -------------------------

y_pred_svm = svm.predict(
    X_test_scaled
)

y_prob_svm = svm.predict_proba(
    X_test_scaled
)[:,1]

# -------------------------
# Métricas
# -------------------------

acc_svm = accuracy_score(
    y_test,
    y_pred_svm
)

prec_svm = precision_score(
    y_test,
    y_pred_svm,
    zero_division=0
)

rec_svm = recall_score(
    y_test,
    y_pred_svm,
    zero_division=0
)

f1_svm = f1_score(
    y_test,
    y_pred_svm,
    zero_division=0
)

auc_svm = roc_auc_score(
    y_test,
    y_prob_svm
)

print("\n📊 Métricas")

print(f"Accuracy : {acc_svm:.4f}")
print(f"Precision: {prec_svm:.4f}")
print(f"Recall   : {rec_svm:.4f}")
print(f"F1-score : {f1_svm:.4f}")
print(f"ROC-AUC  : {auc_svm:.4f}")

# -------------------------
# Classification Report
# -------------------------

print("\n📋 Classification Report")

print(
    classification_report(
        y_test,
        y_pred_svm,
        zero_division=0
    )
)

# -------------------------
# Matriz de Confusão
# -------------------------

cm_svm = confusion_matrix(
    y_test,
    y_pred_svm
)

fig, ax = plt.subplots(
    figsize=(6,5)
)

ConfusionMatrixDisplay(
    confusion_matrix=cm_svm
).plot(
    ax=ax,
    colorbar=False
)

plt.title(
    'SVM - Matriz de Confusão'
)

plt.show()

# -------------------------
# Curva ROC
# -------------------------

fig, ax = plt.subplots(
    figsize=(6,5)
)

RocCurveDisplay.from_predictions(
    y_test,
    y_prob_svm,
    ax=ax
)

plt.title(
    'SVM - Curva ROC'
)

plt.show()

# -------------------------
# Distribuição das Probabilidades
# -------------------------

plt.figure(figsize=(8,5))

sns.histplot(
    y_prob_svm,
    bins=20,
    kde=True
)

plt.title(
    'Distribuição das Probabilidades Previstas (SVM)'
)

plt.xlabel(
    'Probabilidade de Óbito'
)

plt.ylabel(
    'Frequência'
)

plt.grid(alpha=0.3)

plt.show()

# -------------------------
# Casos classificados
# -------------------------

resultado_predicoes = pd.DataFrame({
    'Real': y_test.values,
    'Predito': y_pred_svm,
    'Probabilidade_Obito': y_prob_svm
})

print("\n📋 Exemplo de Predições")

display(
    resultado_predicoes.head(10)
)

# -------------------------
# Salvar Resultados
# -------------------------

resultado_svm = {
    'Modelo': 'SVM',
    'Accuracy': acc_svm,
    'Precision': prec_svm,
    'Recall': rec_svm,
    'F1': f1_svm,
    'ROC_AUC': auc_svm
}

print("\n✅ SVM concluída")

"""## ⚰️ 11) MLP (Multilayer Perceptron)"""

# =========================================
# 11.0 - MLP
# =========================================

from sklearn.neural_network import MLPClassifier

print("\n🧠 Multilayer Perceptron (MLP)")

# -------------------------
# Modelo
# -------------------------

mlp = MLPClassifier(
    hidden_layer_sizes=(32,16),
    activation='relu',
    solver='adam',
    alpha=0.0001,
    learning_rate='adaptive',
    max_iter=500,
    random_state=42
)

mlp.fit(
    X_train_scaled,
    y_train
)

# -------------------------
# Predições
# -------------------------

y_pred_mlp = mlp.predict(
    X_test_scaled
)

y_prob_mlp = mlp.predict_proba(
    X_test_scaled
)[:,1]

# -------------------------
# Métricas
# -------------------------

acc_mlp = accuracy_score(
    y_test,
    y_pred_mlp
)

prec_mlp = precision_score(
    y_test,
    y_pred_mlp,
    zero_division=0
)

rec_mlp = recall_score(
    y_test,
    y_pred_mlp,
    zero_division=0
)

f1_mlp = f1_score(
    y_test,
    y_pred_mlp,
    zero_division=0
)

auc_mlp = roc_auc_score(
    y_test,
    y_prob_mlp
)

print("\n📊 Métricas")

print(f"Accuracy : {acc_mlp:.4f}")
print(f"Precision: {prec_mlp:.4f}")
print(f"Recall   : {rec_mlp:.4f}")
print(f"F1-score : {f1_mlp:.4f}")
print(f"ROC-AUC  : {auc_mlp:.4f}")

# -------------------------
# Classification Report
# -------------------------

print("\n📋 Classification Report")

print(
    classification_report(
        y_test,
        y_pred_mlp,
        zero_division=0
    )
)

# -------------------------
# Matriz de Confusão
# -------------------------

cm_mlp = confusion_matrix(
    y_test,
    y_pred_mlp
)

fig, ax = plt.subplots(
    figsize=(6,5)
)

ConfusionMatrixDisplay(
    confusion_matrix=cm_mlp
).plot(
    ax=ax,
    colorbar=False
)

plt.title(
    'MLP - Matriz de Confusão'
)

plt.show()

# -------------------------
# Curva ROC
# -------------------------

fig, ax = plt.subplots(
    figsize=(6,5)
)

RocCurveDisplay.from_predictions(
    y_test,
    y_prob_mlp,
    ax=ax
)

plt.title(
    'MLP - Curva ROC'
)

plt.show()

# -------------------------
# Evolução do Treinamento
# -------------------------

plt.figure(figsize=(8,5))

plt.plot(
    mlp.loss_curve_
)

plt.title(
    'MLP - Curva de Perda'
)

plt.xlabel(
    'Épocas'
)

plt.ylabel(
    'Loss'
)

plt.grid(alpha=0.3)

plt.show()

# -------------------------
# Número de Épocas
# -------------------------

print(
    f"\n📈 Número de épocas executadas: {mlp.n_iter_}"
)

print(
    f"Loss final: {mlp.loss_:.6f}"
)

# -------------------------
# Predições
# -------------------------

resultado_predicoes_mlp = pd.DataFrame({
    'Real': y_test.values,
    'Predito': y_pred_mlp,
    'Probabilidade_Obito': y_prob_mlp
})

print("\n📋 Exemplo de Predições")

display(
    resultado_predicoes_mlp.head(10)
)

# -------------------------
# Salvar Resultados
# -------------------------

resultado_mlp = {
    'Modelo': 'MLP',
    'Accuracy': acc_mlp,
    'Precision': prec_mlp,
    'Recall': rec_mlp,
    'F1': f1_mlp,
    'ROC_AUC': auc_mlp
}

print("\n✅ MLP concluída")

"""## ⚰️ 12) Random Survival Forest"""

# =========================
# 12.0 - RANDOM SURVIVAL FOREST
# =========================

train_df = train_df.copy()
test_df = test_df.copy()

y_train = Surv.from_dataframe(
    event='evento',
    time='tempo_obito',
    data=train_df
)

y_test = Surv.from_dataframe(
    event='evento',
    time='tempo_obito',
    data=test_df
)

X_train = train_df[features]
X_test = test_df[features]

rsf = RandomSurvivalForest(
    n_estimators=100,
    min_samples_split=10,
    min_samples_leaf=5,
    max_features="sqrt",
    n_jobs=-1,
    random_state=42
)

rsf.fit(X_train, y_train)

print("RSF treinado com sucesso")

# =========================
# 12.1 - Importância das variáveis
# =========================

perm = permutation_importance(
    rsf,
    X_test,
    y_test,
    n_repeats=5,
    random_state=42,
    n_jobs=-1
)

importances = pd.Series(
    perm.importances_mean,
    index=features
).sort_values(ascending=False)

print(importances)

plt.figure(figsize=(8,5))
sns.barplot(x=importances.values, y=importances.index)
plt.title("Importância das Variáveis — RSF")
plt.grid(alpha=0.3)
plt.show()

# =========================
# 12.2 - Performance Final
# =========================

rsf_pred = rsf.predict(X_test)

rsf_cindex = concordance_index_censored(
    y_test["evento"],
    y_test["tempo_obito"],
    rsf_pred
)[0]

print("C-index Cox:", cox_cindex)
print("C-index RSF:", rsf_cindex)

comparacao = pd.DataFrame({
    "Modelo": ["Cox PH", "RSF"],
    "C-index": [cox_cindex, rsf_cindex]
})

display(comparacao)

# =========================
# 12.3 - Curvas RSF
# =========================

sample = np.random.choice(len(X_test), 5, replace=False)

surv_funcs = rsf.predict_survival_function(X_test.iloc[sample])

plt.figure(figsize=(8,5))

for i, fn in enumerate(surv_funcs):
    plt.step(fn.x, fn(fn.x), where="post", label=f"Paciente {i+1}")

plt.title("Curvas de Sobrevivência — RSF")
plt.xlabel("Tempo (semanas)")
plt.ylabel("Probabilidade de Sobrevivência")
plt.legend()
plt.grid(alpha=0.3)
plt.show()

# =========================
# RESUMO FINAL DA AMOSTRA
# =========================

# Amostra utilizada nos testes Log-Rank (IG)
if 'faixa_ig' in df_surv_ig.columns:
    total_logrank = df_surv_ig['faixa_ig'].notna().sum()
    print("Total log-rank:", total_logrank)
else:
    print("⚠️ Coluna 'faixa_ig' não encontrada em df_surv_ig")

# Amostra utilizada na modelagem
total_modelagem = len(train_df) + len(test_df)

print("\n📊 Amostra de Modelagem")
print("Total modelagem:", total_modelagem)
print("Treino:", len(train_df))
print("Teste:", len(test_df))

# Eventos e censuras
df_model = pd.concat([train_df, test_df], ignore_index=True)

eventos = int(df_model['evento'].sum())
censurados = int((df_model['evento'] == 0).sum())

print("\n⚰️ Desfechos")
print("Eventos (óbito):", eventos)
print("Censurados:", censurados)
print("Soma:", eventos + censurados)

# Performance final
print("\n🎯 Performance")
print(f"C-index Cox: {cox_cindex:.4f}")
print(f"C-index RSF: {rsf_cindex:.4f}")

"""## ⚰️ 13) Comparação dos Modelos"""

# =========================================
# 13.0 - COMPARAÇÃO DOS MODELOS
# =========================================

print("\n🏆 Comparação Final dos Modelos")

# -------------------------
# Classificadores
# -------------------------

comparacao_ml = pd.DataFrame([
    resultado_lr,
    resultado_tree,
    resultado_svm,
    resultado_mlp
])

comparacao_ml = comparacao_ml.round(4)

print("\n📊 Modelos de Classificação")

display(comparacao_ml)

# -------------------------
# Melhor modelo
# -------------------------

melhor_auc = comparacao_ml.loc[
    comparacao_ml['ROC_AUC'].idxmax()
]

print("\n🥇 Melhor ROC-AUC")

print(
    f"{melhor_auc['Modelo']} "
    f"({melhor_auc['ROC_AUC']:.4f})"
)

# -------------------------
# Gráfico ROC-AUC
# -------------------------

plt.figure(figsize=(8,5))

sns.barplot(
    data=comparacao_ml,
    x='Modelo',
    y='ROC_AUC'
)

plt.title(
    'Comparação dos Modelos - ROC AUC'
)

plt.ylabel(
    'ROC-AUC'
)

plt.ylim(0,1)

plt.grid(
    axis='y',
    alpha=0.3
)

plt.show()

# -------------------------
# Accuracy
# -------------------------

plt.figure(figsize=(8,5))

sns.barplot(
    data=comparacao_ml,
    x='Modelo',
    y='Accuracy'
)

plt.title(
    'Comparação dos Modelos - Accuracy'
)

plt.ylabel(
    'Accuracy'
)

plt.ylim(0,1)

plt.grid(
    axis='y',
    alpha=0.3
)

plt.show()

# -------------------------
# F1 Score
# -------------------------

plt.figure(figsize=(8,5))

sns.barplot(
    data=comparacao_ml,
    x='Modelo',
    y='F1'
)

plt.title(
    'Comparação dos Modelos - F1 Score'
)

plt.ylabel(
    'F1 Score'
)

plt.ylim(0,1)

plt.grid(
    axis='y',
    alpha=0.3
)

plt.show()

# =========================================
# 13.0 - COMPARAÇÃO DOS MODELOS
# =========================================

print("\n🏆 Comparação Final dos Modelos")

# -------------------------
# Classificadores
# -------------------------

comparacao_ml = pd.DataFrame([
    resultado_lr,
    resultado_tree,
    resultado_svm,
    resultado_mlp
])

comparacao_ml = comparacao_ml.round(4)

print("\n📊 Modelos de Classificação")

display(comparacao_ml)

# -------------------------
# Melhor modelo
# -------------------------

melhor_auc = comparacao_ml.loc[
    comparacao_ml['ROC_AUC'].idxmax()
]

print("\n🥇 Melhor ROC-AUC")

print(
    f"{melhor_auc['Modelo']} "
    f"({melhor_auc['ROC_AUC']:.4f})"
)

# -------------------------
# Gráfico ROC-AUC
# -------------------------

plt.figure(figsize=(8,5))

sns.barplot(
    data=comparacao_ml,
    x='Modelo',
    y='ROC_AUC'
)

plt.title(
    'Comparação dos Modelos - ROC AUC'
)

plt.ylabel(
    'ROC-AUC'
)

plt.ylim(0,1)

plt.grid(
    axis='y',
    alpha=0.3
)

plt.show()

# -------------------------
# Accuracy
# -------------------------

plt.figure(figsize=(8,5))

sns.barplot(
    data=comparacao_ml,
    x='Modelo',
    y='Accuracy'
)

plt.title(
    'Comparação dos Modelos - Accuracy'
)

plt.ylabel(
    'Accuracy'
)

plt.ylim(0,1)

plt.grid(
    axis='y',
    alpha=0.3
)

plt.show()

# -------------------------
# F1 Score
# -------------------------

plt.figure(figsize=(8,5))

sns.barplot(
    data=comparacao_ml,
    x='Modelo',
    y='F1'
)

plt.title(
    'Comparação dos Modelos - F1 Score'
)

plt.ylabel(
    'F1 Score'
)

plt.ylim(0,1)

plt.grid(
    axis='y',
    alpha=0.3
)

plt.show()