# -*- coding: utf-8 -*-
"""PCA

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lIrM29FRWcftME3O3fz9NpeVjWk12z-p

## Desafio PCA - Visualização de Dados Multivariados

## Atividade Avaliativa

### Membros

Edson Maciel e Barros Junior - 20210010250

Neste desafio, aplicamos a técnica de Análise de Componentes Principais (PCA) para um problema de redução de dimensionalidade e visualização de dados multivariados.

O objetivo é transformar dados de alta dimensão em um espaço de menor dimensão, preservando o máximo possível da variância dos dados.

Esse problema é um exemplo clássico de aprendizado não supervisionado, utilizado principalmente para exploração e visualização de dados.

Neste trabalho, reduzimos os dados para duas componentes principais, permitindo a visualização em 2D e facilitando a interpretação da estrutura dos dados.

## 📌 Objetivo do PCA:
0 - Reduzir a dimensionalidade dos dados  
1 - Manter a maior variância possível  
2 - Facilitar visualização e interpretação  
3 - Identificar padrões e separação entre grupos
"""

# =========================
# 0. IMPORTAÇÃO DAS BIBLIOTECAS
# =========================

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.datasets import load_wine
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.datasets import load_iris

# =========================
# 1. CARREGAR BASE DE DADOS
# =========================

iris = load_iris()

X = iris.data
y = iris.target

# criar dataframe
df = pd.DataFrame(
    iris.data,
    columns=iris.feature_names
)

# adicionar classe
df['classe'] = iris.target

print(df.head())

# =========================
# 2. NORMALIZAÇÃO DOS DADOS
# =========================

X = df.drop('classe', axis=1)

scaler = StandardScaler()

X_normalizado = scaler.fit_transform(X)

# =========================
# 3. TREINAR PCA
# =========================

pca = PCA(n_components=2)

X_pca = pca.fit_transform(X_normalizado)

# criar dataframe PCA
df_pca = pd.DataFrame(
    X_pca,
    columns=['PC1', 'PC2']
)

df_pca['classe'] = iris.target

# =========================
# VARIÂNCIA EXPLICADA
# =========================

print("Variância explicada:")
print(pca.explained_variance_ratio_)

# =========================
# 4. VISUALIZAÇÃO
# =========================

plt.figure(figsize=(10, 6))

cores = ['red', 'green', 'blue']

for classe, cor in zip(df_pca['classe'].unique(), cores):

    dados = df_pca[df_pca['classe'] == classe]

    plt.scatter(
        dados['PC1'],
        dados['PC2'],
        color=cor,
        label=iris.target_names[classe]
    )

plt.xlabel('Primeiro Componente Principal (PC1)')
plt.ylabel('Segundo Componente Principal (PC2)')
plt.title('Visualização da Base Iris usando PCA')
plt.legend()
plt.grid(True)
plt.show()

"""## Conclusão

A aplicação da Análise de Componentes Principais (PCA) mostrou-se eficiente para a redução de dimensionalidade e visualização dos dados em um espaço bidimensional.

A transformação dos dados originais em componentes principais permitiu preservar a maior parte da variância, facilitando a interpretação da estrutura dos dados.

A projeção em 2D evidenciou a formação de agrupamentos naturais entre as classes, indicando que os dados possuem padrões bem definidos mesmo após a redução de dimensionalidade.

De forma geral, o PCA se mostrou uma ferramenta eficaz para exploração, visualização e análise preliminar de dados multivariados, sendo especialmente útil em problemas de aprendizado de máquina.

"""