# -*- coding: utf-8 -*-
"""rede-cnn.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EjS6L1aT01XuMmNh2K5JsEkBW_F0jA8M

#REDE CONVOLUCIONAL - FASHION MNIST

Automatically generated by Colab.

## Desafio Fashion MNIST - CNN

## Atividade Avaliativa

### Membros

Edson Maciel e Barros Junior - 20210010250

Neste desafio, aplicamos uma **Rede Neural Convolucional (CNN)** para um problema de classificação de imagens.

O objetivo é classificar peças de roupa da base Fashion MNIST.

Esse problema é um exemplo clássico de **aprendizado supervisionado (classificação)** com imagens.

## 📌 Classes:
0 - T-shirt/top  
1 - Trouser  
2 - Pullover  
3 - Dress  
4 - Coat  
5 - Sandal  
6 - Shirt  
7 - Sneaker  
8 - Bag  
9 - Ankle boot
"""

# ==============================
# IMPORTAÇÃO DAS BIBLIOTECAS
# ==============================

import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense, Dropout
from sklearn.metrics import confusion_matrix, classification_report
import seaborn as sns

# ==============================
# CARREGAMENTO DOS DADOS
# ==============================

(X_train, y_train), (X_test, y_test) = tf.keras.datasets.fashion_mnist.load_data()

print("Treino:", X_train.shape)
print("Teste:", X_test.shape)

# ==============================
# VISUALIZAÇÃO DOS DADOS
# ==============================

classes = [
    "T-shirt/top", "Trouser", "Pullover", "Dress", "Coat",
    "Sandal", "Shirt", "Sneaker", "Bag", "Ankle boot"
]

plt.figure(figsize=(10,5))

for i in range(10):
    plt.subplot(2,5,i+1)
    plt.imshow(X_train[i], cmap='gray')
    plt.title(classes[y_train[i]])
    plt.axis('off')

plt.show()

# ==============================
# TRATAMENTO DOS DADOS
# ==============================

# Normalização
X_train = X_train / 255.0
X_test = X_test / 255.0

# Ajuste de dimensão (CNN precisa de canal)
X_train = X_train.reshape(-1,28,28,1)
X_test = X_test.reshape(-1,28,28,1)

# One-hot encoding
y_train_cat = tf.keras.utils.to_categorical(y_train, 10)
y_test_cat = tf.keras.utils.to_categorical(y_test, 10)

# ==============================
# CONSTRUÇÃO DA CNN
# ==============================

modelo = Sequential()

modelo.add(Conv2D(32, (3,3), activation='relu', input_shape=(28,28,1)))
modelo.add(MaxPooling2D(2,2))

modelo.add(Conv2D(64, (3,3), activation='relu'))
modelo.add(MaxPooling2D(2,2))

modelo.add(Flatten())

modelo.add(Dense(128, activation='relu'))
modelo.add(Dropout(0.2))

modelo.add(Dense(10, activation='softmax'))

modelo.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

modelo.summary()

# ==============================
# TREINAMENTO
# ==============================

history = modelo.fit(
    X_train, y_train_cat,
    epochs=10,
    batch_size=64,
    validation_data=(X_test, y_test_cat)
)

# ==============================
# AVALIAÇÃO
# ==============================

loss, acc = modelo.evaluate(X_test, y_test_cat)

print(f"Acurácia: {acc:.4f}")

# ==============================
# MATRIZ DE CONFUSÃO
# ==============================

y_pred = modelo.predict(X_test)
y_pred_classes = np.argmax(y_pred, axis=1)

cm = confusion_matrix(y_test, y_pred_classes)

plt.figure()
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues')

plt.title("Matriz de Confusão")
plt.xlabel("Predito")
plt.ylabel("Real")

plt.show()

# ==============================
# RELATÓRIO DE CLASSIFICAÇÃO
# ==============================

print("\nRelatório:")
print(classification_report(y_test, y_pred_classes, target_names=classes))

# ==============================
# GRÁFICO DE ACURÁCIA
# ==============================

plt.figure()

plt.plot(history.history['accuracy'])
plt.plot(history.history['val_accuracy'])

plt.title("Acurácia do Modelo")
plt.xlabel("Épocas")
plt.ylabel("Acurácia")
plt.legend(["Treino", "Validação"])

plt.show()

# ==============================
# GRÁFICO DE LOSS
# ==============================

plt.figure()

plt.plot(history.history['loss'])
plt.plot(history.history['val_loss'])

plt.title("Loss do Modelo")
plt.xlabel("Épocas")
plt.ylabel("Loss")
plt.legend(["Treino", "Validação"])

plt.show()

# ==============================
# TESTE COM UMA IMAGEM
# ==============================

import random

idx = random.randint(0, len(X_test))

plt.imshow(X_test[idx].reshape(28,28), cmap='gray')
plt.title("Imagem de teste")
plt.axis('off')
plt.show()

pred = modelo.predict(X_test[idx].reshape(1,28,28,1))

print("Classe prevista:", classes[np.argmax(pred)])

# ==============================
# DISTRIBUIÇÃO DAS CLASSES
# ==============================

plt.figure()

unique, counts = np.unique(y_train, return_counts=True)

plt.bar(unique, counts)
plt.xticks(unique, classes, rotation=45)

plt.title("Distribuição das Classes")
plt.xlabel("Classe")
plt.ylabel("Quantidade")

plt.show()

"""## Conclusão

A Rede Convolucional apresentou excelente desempenho na classificação das imagens da base Fashion MNIST.

A utilização de camadas convolucionais permitiu extrair características relevantes das imagens, melhorando a capacidade de generalização do modelo.

Os gráficos de acurácia e loss mostraram boa convergência durante o treinamento.

A matriz de confusão evidenciou que algumas classes visualmente semelhantes (como camisa e camiseta) podem gerar confusão no modelo.

De forma geral, a CNN demonstrou ser altamente eficaz para problemas de classificação de imagens.
"""