# -*- coding: utf-8 -*-
"""Rede convolucional - Fashion MNIST.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15DMm3Qf3IcN-syiNIvy_O04N5k9bBZV6

# Rede Convolucional - MNIST - Moda
* _Fashion_ MNIST é uma base de dados clássica contendo imagens de alguns objetos de uso pessoal.
* A rede convolucional é um modelo clássico para tarefas de classificação em imagens. Mas pode ser aplicada em outros tipos problemas.

## Referência
* Curso: The Complete Self-Driving Car Course - Udemy
* https://keras.io/api/datasets/fashion_mnist/

## Carregando os dados
"""

import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf

np.random.seed(0)


(X_train, y_train), (X_test, y_test)= tf.keras.datasets.fashion_mnist.load_data()

print(X_train.shape)
print(X_test.shape)
print(y_train.shape)

print(y_train[1])
print(X_train.shape)
print(y_train == 1)

"""## Visualização dos dados"""

import random
num_of_samples=[]

cols = 5
num_classes = 10

fig, axs = plt.subplots(nrows=num_classes, ncols=cols, figsize=(5,10))
fig.tight_layout()

for i in range(cols):
    for j in range(num_classes):
      x_selected = X_train[y_train == j]
      axs[j][i].imshow(x_selected[random.randint(0,(len(x_selected) - 1)), :, :], cmap=plt.get_cmap('gray'))
      axs[j][i].axis("off")
      if i == 2:
        axs[j][i].set_title(str(j))
        num_of_samples.append(len(x_selected))

"""## Tratando os dados para treinamento"""

print(num_of_samples)
plt.figure(figsize=(12, 4))
plt.bar(range(0, num_classes), num_of_samples)
plt.title("Distribuição das amostras de treinamento")
plt.xlabel("Classes / Números")
plt.ylabel("Quantidade de imagens")
plt.show()

X_train = X_train.reshape(60000, 28, 28, 1)
X_test = X_test.reshape(10000, 28, 28, 1)

# Convertendo a saída de um número inteiro para vetor com dez posições
## Todos zerados, mas com valor um na posição da respectiva classe
y_train = tf.keras.utils.to_categorical( y_train,10)
y_test = tf.keras.utils.to_categorical(y_test, 10)

# convertendo para valres entre 0 e 1
X_train = X_train/255
X_test = X_test/255

"""## Treinamento

### Construíndo a estrutura da rede
"""





"""### Treinando"""



"""## Avaliação do treinamento"""









