# -*- coding: utf-8 -*-
"""ÁRVORE DE DECISÃO - PARKINSONS

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18zjBQe6N9CQXLDb4yE5WwCh5q9oc9WBY

# Desafio da Diabetes - Árvore de Decisão

# Atividade Avaliativa

### Membros

Edson Macield e Barros Junior - 20210010250


Neste desafio, aplicamos o algoritmo de **Árvore de Decisão** para um problema de classificação.

O objetivo é classificar as espécies da flor Iris com base em suas características físicas.

Esse problema foi estudado em aula como exemplo de **aprendizado supervisionado (classificação)**.

## 📌 Atributos utilizados:
- Comprimento da sépala
- Largura da sépala
- Comprimento da pétala
- Largura da pétala

## 🎯 Saída:
- Espécie da flor (Setosa, Versicolor ou Virginica)
"""

# ==============================
# IMPORTAÇÃO DAS BIBLIOTECAS
# ==============================

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier, plot_tree
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
import seaborn as sns

# ==============================
# CARREGAMENTO DE DADOS
# ==============================

# Carregando o dataset
df = pd.read_csv("Parkinsons-Telemonitoring-ucirvine.csv")

# Visualizando
df.head()

# ==============================
# ANÁLISE INICIAL
# ==============================

df.info()
df.describe()

print(df.columns)

# ==============================
# TRATAMENTO DOS DADOS
# ==============================

# Removendo colunas irrelevantes (se existirem)
colunas_remover = ['subject', 'test_time']

df = df.drop(columns=[col for col in colunas_remover if col in df.columns])

# Criando variável de classificação com base na gravidade total
df['classe'] = df['total_updrs'].apply(
    lambda x: 'grave' if x > 20 else 'leve'
)

# Removendo variável original
df = df.drop(columns=['total_updrs'])

# ==============================
# SEPARAÇÃO DOS DADOS
# ==============================

X = df.drop(columns=['classe'])
y = df['classe']

# Divisão treino/teste
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# ==============================
# TREINAMENTO DA ÁRVORE
# ==============================

modelo = DecisionTreeClassifier(
    max_depth=5,
    criterion='entropy'
)

modelo.fit(X_train, y_train)

# ==============================
# AVALIAÇÃO
# ==============================

y_pred = modelo.predict(X_test)

# Acurácia
acc = accuracy_score(y_test, y_pred)
print(f"Acurácia: {acc:.4f}")

# Relatório completo
print("\nRelatório:")
print(classification_report(y_test, y_pred))

# ==============================
# MATRIZ DE CONFUSÃO
# ==============================

cm = confusion_matrix(y_test, y_pred)

plt.figure()
sns.heatmap(cm, annot=True, fmt='d')

plt.title("Matriz de Confusão")
plt.xlabel("Predito")
plt.ylabel("Real")

plt.show()

# ==============================
# VISUALIZAÇÃO DA ÁRVORE
# ==============================

plt.figure(figsize=(15, 8))

plot_tree(
    modelo,
    feature_names=X.columns,
    class_names=modelo.classes_,
    filled=True
)

plt.show()

# ==============================
# IMPORTÂNCIA DAS VARIÁVEIS
# ==============================

importancias = modelo.feature_importances_

plt.figure()
plt.barh(X.columns, importancias)

plt.title("Importância das Variáveis")

plt.show()

# ==============================
# TESTE DE PROFUNDIDADE
# ==============================

profundidades = []
acuracias = []

for depth in range(1, 10):
    modelo_temp = DecisionTreeClassifier(max_depth=depth)
    modelo_temp.fit(X_train, y_train)

    y_pred_temp = modelo_temp.predict(X_test)
    acc_temp = accuracy_score(y_test, y_pred_temp)

    profundidades.append(depth)
    acuracias.append(acc_temp)

plt.figure()
plt.plot(profundidades, acuracias)

plt.title("Acurácia vs Profundidade")
plt.xlabel("Profundidade")
plt.ylabel("Acurácia")

plt.show()

# ==============================
# TESTE DE PROFUNDIDADE
# ==============================

plt.figure(figsize=(10,6))
corr = df.corr(numeric_only=True)

sns.heatmap(corr, cmap='coolwarm')
plt.title("Matriz de Correlação")

plt.show()

# ==============================
# Correlação entre variáveis
# ==============================

plt.figure(figsize=(10,6))
corr = df.corr(numeric_only=True)

sns.heatmap(corr, cmap='coolwarm')
plt.title("Matriz de Correlação")

plt.show()

# ==============================
# Distribuição das classes
# ==============================

plt.figure()

df['classe'].value_counts().plot(kind='bar')

plt.title("Distribuição das Classes")
plt.xlabel("Classe")
plt.ylabel("Quantidade")

plt.show()

# ==============================
# Boxplot (outliers)
# ==============================

plt.figure(figsize=(10,5))

sns.boxplot(data=df[['age', 'jitter', 'shimmer']])

plt.title("Boxplot das Variáveis")

plt.show()

# ==============================
# Testar diferentes critérios
# ==============================

for crit in ['gini', 'entropy']:
    modelo_temp = DecisionTreeClassifier(criterion=crit)
    modelo_temp.fit(X_train, y_train)

    y_pred_temp = modelo_temp.predict(X_test)
    acc = accuracy_score(y_test, y_pred_temp)

    print(f"{crit}: {acc:.4f}")

# ==============================
# Ver profundidade da árvore
# ==============================

print("Profundidade da árvore:", modelo.get_depth())
print("Número de folhas:", modelo.get_n_leaves())

# ==============================
# Comparar com Random Forest
# ==============================

from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(n_estimators=100)
rf.fit(X_train, y_train)

y_pred_rf = rf.predict(X_test)

print("Acurácia Random Forest:", accuracy_score(y_test, y_pred_rf))

# ==============================
# Feature importance MAIS BONITO
# ==============================

importancias = modelo.feature_importances_

indices = np.argsort(importancias)

plt.figure()
plt.barh(range(len(indices)), importancias[indices])
plt.yticks(range(len(indices)), X.columns[indices])

plt.title("Importância das Variáveis")

plt.show()

"""## Conclusão

A Árvore de Decisão apresentou bom desempenho na classificação da gravidade da doença de Parkinson.

A transformação do problema de regressão em classificação permitiu aplicar técnicas de aprendizado supervisionado de forma eficaz.

A análise da importância das variáveis mostrou quais características vocais são mais relevantes para a predição.

Além disso, o ajuste da profundidade da árvore demonstrou impacto direto no desempenho do modelo, evidenciando a importância do controle de complexidade.
"""