# -*- coding: utf-8 -*-
"""Aprendizado de Maquina - Regressão Linear

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/152OER6hxmIpg8fcPyTwE8HD8nmIhPIHZ

# Desafio do Aluguel - Regressão Linear

# Atividade Avaliativa

### Membros

Edson Macield e Barros Junior - 20210010250


Nesta atividade, aplicamos os conceitos de aprendizado de máquina vistos em aula para resolver um problema de regressão.

O objetivo é prever o valor de aluguel de imóveis com base em suas características, como tipo, bairro, número de quartos, vagas, área, condomínio e IPTU.

Diferente do exemplo anterior (regressão simples), este problema utiliza múltiplas variáveis, caracterizando uma Regressão Linear Múltipla.

Ferramentas utilizadas:
- Python
- Pandas
- Scikit-Learn
"""

# ==============================
# 1. IMPORTAÇÃO DAS BIBLIOTECAS
# ==============================
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, r2_score

# ==========================================
# REGRESSÃO LINEAR SIMPLES (CASAS)
# ==========================================

url = "https://raw.githubusercontent.com/ect-info/ml/master/dados/preco_casas.csv"
df = pd.read_csv(url)

X = df[['Área (m²)']].values
y = df['Preço (R$)'].values

modelo_simples = LinearRegression()
modelo_simples.fit(X, y)

y_pred = modelo_simples.predict(X)

plt.figure()
plt.scatter(X, y)
plt.plot(X, y_pred)
plt.title("Regressão Linear Simples")
plt.xlabel("Área (m²)")
plt.ylabel("Preço")
plt.show()

plt.figure()
plt.scatter(y, y_pred)
plt.title("Real vs Predito (Casas)")
plt.xlabel("Real")
plt.ylabel("Predito")
plt.show()

area = 110
preco = modelo_simples.predict([[area]])
print(f"Preço estimado (110m²): R$ {preco[0]:.2f}")

# ==========================================
# DESAFIO DO ALUGUEL
# ==========================================
url_aluguel = "https://raw.githubusercontent.com/ect-info/ml/master/dados/aluguel_residencial.csv"
data = pd.read_csv(url_aluguel, sep=";")

data = data.dropna()

X = data[['Tipo', 'Bairro', 'Quartos', 'Vagas', 'Area', 'Condominio', 'IPTU']]
y = data['Valor']

X = pd.get_dummies(X)

X_treino, X_teste, y_treino, y_teste = train_test_split(X, y, test_size=0.2, random_state=42)

# ==============================
# MODELO 2 - RANDOM FOREST
# ==============================
modelo_lr = LinearRegression()
modelo_lr.fit(X_treino, y_treino)

y_pred_lr = modelo_lr.predict(X_teste)

mse_lr = mean_squared_error(y_teste, y_pred_lr)
r2_lr = r2_score(y_teste, y_pred_lr)

# ==============================
# COMPARAÇÃO DOS MODELOS
# ==============================
print("\n=== Comparação de Modelos ===")
print(f"Regressão Linear -> MSE: {mse_lr:.2f} | R²: {r2_lr:.4f}")
print(f"Random Forest   -> MSE: {mse_rf:.2f} | R²: {r2_rf:.4f}")

# ==============================
# GRÁFICOS
# ==============================

# Real vs Predito (Linear)
plt.figure()
plt.scatter(y_teste, y_pred_lr)
plt.title("Linear - Real vs Predito")
plt.xlabel("Real")
plt.ylabel("Predito")
plt.show()

# Real vs Predito (Random Forest)
plt.figure()
plt.scatter(y_teste, y_pred_rf)
plt.title("Random Forest - Real vs Predito")
plt.xlabel("Real")
plt.ylabel("Predito")
plt.show()

# Histograma
plt.figure()
plt.hist(y, bins=30)
plt.title("Distribuição dos Aluguéis")
plt.xlabel("Preço")
plt.ylabel("Frequência")
plt.show()

# Área vs preço
plt.figure()
plt.scatter(data['Area'], data['Valor'])
plt.title("Área vs Preço do Aluguel")
plt.xlabel("Área")
plt.ylabel("Preço")
plt.show()

# Importância das variáveis (Random Forest)
importancias = modelo_rf.feature_importances_
indices = np.argsort(importancias)[-10:]

plt.figure()
plt.barh(range(len(indices)), importancias[indices])
plt.yticks(range(len(indices)), [X.columns[i] for i in indices])
plt.title("Importância das Variáveis")
plt.show()

# ==============================
# PREDIÇÃO FINAL
# ==============================

novo_imovel = pd.DataFrame([{
    'Tipo': 'Apartamento',
    'Bairro': 'Centro',
    'Quartos': 2,
    'Vagas': 1,
    'Area': 80,
    'Condominio': 700,
    'IPTU': 400
}])

novo_imovel = pd.get_dummies(novo_imovel)
novo_imovel = novo_imovel.reindex(columns=X.columns, fill_value=0)

preco_lr = modelo_lr.predict(novo_imovel)
preco_rf = modelo_rf.predict(novo_imovel)

print(f"\nPreço (Linear): R$ {preco_lr[0]:.2f}")
print(f"Preço (Random Forest): R$ {preco_rf[0]:.2f}")

# ==========================================
# CONCLUSÃO
# ==========================================

print("\nConclusão:")
print("Foram utilizados dois modelos: Regressão Linear e Random Forest.")
print("O Random Forest geralmente apresenta melhor desempenho por capturar relações não lineares.")
print("O uso de múltiplas variáveis melhora significativamente a capacidade preditiva do modelo.")

"""## Conclusão

A Regressão Linear Múltipla permitiu modelar a relação entre diversas características do imóvel e o valor do aluguel.

Foi necessário realizar o tratamento de dados categóricos, convertendo variáveis textuais em numéricas para que o modelo pudesse processá-las corretamente.

O modelo foi avaliado utilizando o Erro Quadrático Médio (MSE), indicando o nível de precisão das previsões.

Essa atividade possibilitou aplicar na prática os conceitos de aprendizado supervisionado, além de demonstrar um cenário mais próximo de problemas reais de Machine Learning.
"""