# -*- coding: utf-8 -*-
"""Aprendizado de Maquina - Regressão Linear

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/152OER6hxmIpg8fcPyTwE8HD8nmIhPIHZ

# Regressão Linear - Previsão de Preço de Casas

Neste notebook, aplicamos na prática os conceitos de **Regressão Linear Simples** vistos em aula, com o objetivo de compreender como modelos de aprendizado de máquina podem ser utilizados para prever valores contínuos.

O problema abordado consiste em estimar o preço de uma casa com base na sua área em metros quadrados. Para isso, utilizamos uma base de dados simples, composta por dois atributos:

- Área da casa (m²) — variável independente (entrada)
- Preço da casa (R$) — variável dependente (saída)

Durante a atividade, utilizamos ferramentas amplamente empregadas em Machine Learning, como:
- **Python** para implementação
- **Pandas** para manipulação dos dados
- **Matplotlib** para visualização gráfica
- **Scikit-Learn** para construção e treinamento do modelo

A proposta deste notebook é reforçar, de forma prática, o conteúdo estudado em sala, permitindo a compreensão do processo completo de um modelo supervisionado, desde a leitura dos dados até a realização de previsões.
"""

# Importação das bibliotecas
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression

"""Carreguei o conjunto de dados utilizando a biblioteca Pandas.

Com o DataFrame, visualizei e manipulei os dados de forma estruturada.
"""

url = "https://raw.githubusercontent.com/ect-info/ml/master/dados/preco_casas.csv"

# Carregando os dados em um DataFrame do pandas
df = pd.read_csv(url)

# Mostrando as primeiras linhas da base
df.head()

"""X representa a variável de entrada (área da casa) e o Y representa a variável que queremos prever (preço)."""

# Selecionando a variável independente (Área da casa)
X = df[['Área (m²)']].values

# Selecionando a variável dependente (Preço da casa)
y = df['Preço (R$)'].values

# Visualizando os primeiros valores
print("Primeiros valores de X:")
print(X[:5])

print("\nPrimeiros valores de y:")
print(y[:5])

"""O método fit() ajusta o modelo aos dados de treinamento, calculando a melhor reta que representa a relação entre área e preço."""

# Criando o modelo de regressão linear
modelo = LinearRegression()

# Treinando o modelo com os dados
modelo.fit(X, y)

# Criando um gráfico de dispersão dos dados
plt.scatter(X, y)

plt.xlabel("Área da casa (m²)")
plt.ylabel("Preço da casa (R$)")
plt.title("Distribuição dos dados")

plt.show()

# Gerando as previsões do modelo
y_pred = modelo.predict(X)

# Plotando os dados reais
plt.scatter(X, y, label="Dados reais")

# Plotando a reta de regressão
plt.plot(X, y_pred, color='red', label="Regressão Linear")

plt.xlabel("Área da casa (m²)")
plt.ylabel("Preço da casa (R$)")
plt.legend()

plt.show()

# Área da casa para realizar a previsão
area = 110

# Realizando a predição
preco = modelo.predict([[area]])

print(f"Preço estimado para uma casa de {area} m²: R${preco[0]:.2f}")

"""## Conclusão

A regressão linear simples demonstrou ser uma abordagem eficaz para modelar a relação entre a área de uma casa e seu respectivo preço, permitindo identificar uma tendência linear entre as variáveis analisadas.

A partir do modelo treinado, foi possível realizar estimativas de preço para novos valores de área, evidenciando a capacidade preditiva do algoritmo dentro do domínio dos dados utilizados.

Além disso, esta atividade permitiu consolidar, na prática, os conceitos vistos em aula sobre aprendizado supervisionado, incluindo etapas como preparação dos dados, treinamento do modelo e análise dos resultados.

Embora seja um modelo simples, a regressão linear constitui uma base fundamental para o entendimento de técnicas mais avançadas de Machine Learning, sendo amplamente utilizada como ponto de partida em problemas de regressão.
"""